### ISSUE TITLE
Can we control how the searching works on the search APIs?

### ISSUE THREAD

**Issue by insano10** [b2ihealthcare/snow-owl#1090]
I'm implementing a 'search as you type' widget for snomed codes and I've noticed that the concept/description searching appears to be implemented as a whole word token search. Is there any control over how this works from API parameters?

For example if a user is typing the word "heart attack", there will be some intermediate searches of "heart a" and "heart at". 
I would like the search results to be ordered using prefix matches rather than whole tokens.

Currently:

"heart a" returns “Fear of having a heart attack”
"heart at" returns "Heart rate measured at systemic artery (observable entity)"

I would like both searches to prefer to return "heart attack".

Is there any way of doing this?

And also I was hoping to get the best matching description for the search term from the Concept search API (by expanding the descriptions field) but the descriptions don't appear to be ordered according to their relevance with the inputted search term. Is there any way to specify this? I could only see sorting by particular fields.

Thanks.

**Comment by cmark** [comment]
Hi @insano10,

Prefix matching is supported and it is applied to all lexical searches. When you use either the Concept or the Description API `term` filter the following full-text search will be executed:
1. exact search term matches (lowercase, ascii-folded, etc.)
2. all words of the search term match (lowercase, ascii-folded, etc.)
3. all whole words of the search term and the last word as prefix at any position matches (the one you are looking for basically)
4. all prefixes of the search term match (lowercase, ascii-folded, etc. 2-12 length prefixes)

Scoring is applied in the same order as well, so if a search term matches both an entire description term exactly and it is a prefix of another description term, then the exact match will get a higher score. If more than two descriptions match in the same category then the score depends on the BM25 scorer present in the underlying Elasticsearch search engine. Please note that for performance reasons we only index prefixes between the length of `2-12`.

The analyzers we use can be seen here:
https://github.com/b2ihealthcare/snow-owl/blob/8.x/commons/com.b2international.index/src/com/b2international/index/es/admin/analysis.json
The actual search query can be checked here:
https://github.com/b2ihealthcare/snow-owl/blob/21b5b830561c7747ed47df5de582548e533e4144/core/com.b2international.snowowl.core/src/com/b2international/snowowl/core/request/search/MatchTermFilter.java#L187

Unfortunately, the scoring categories, their order (1-4 above) and the text queries added to the search request cannot be tweaked at the moment. The only things you can change are 
* the ordering (by default when you use a term filter the `_score` sort order is applied, you can enforce this by explicitly specifying it in the `sort` field if you want).
* fuzziness via the `fuzzy` parameter (not exposed to the Concept/Description REST API)
* ignoring stopwords (not exposed to the Concept/Description REST API)
* minShouldMatch (not exposed to the Concept/Description REST API)

> And also I was hoping to get the best matching description for the search term from the Concept search API (by expanding the descriptions field) but the descriptions don't appear to be ordered according to their relevance with the inputted search term. Is there any way to specify this? I could only see sorting by particular fields.

Description expansion only expands the actual descriptions of the matched concepts, but it does not know how these concepts are found by the search request. If you would like to see all matching descriptions in their respective scoring order then I suggest using the Description API.

I hope this clarifies and helps.

Cheers,
Mark

**Comment by insano10** [comment]
That's very helpful, thank you very much for the comprehensive (and quick!) response

**Comment by cmark** [comment]
Glad I could help. 

I think in the long run if this is something users are looking for we will definitely get more configuration supported in the search system, so thank you very much for your information and use case. 🙇

**Comment by insano10** [comment]
That's great to hear you are open to changes as I am keen to use your product. Would you be open to external contributions to this repo to add this configuration in the future?

**Comment by cmark** [comment]
Yeah sure. We have a [CONTRIBUTING document](https://github.com/b2ihealthcare/snow-owl/blob/8.x/CONTRIBUTING.md) describing our contribution policy to this repository.
