### ISSUE TITLE
Error launching snow owl

### ISSUE THREAD

**Issue by vachonr** [b2ihealthcare/snow-owl#1102]
Hello

I have the following message when I launch snoowl.bat
14:57:35.061 [Start Level: Equinox Container: 17aab7b4-b3c6-4aab-856f-bfc4da8023bb] DEBUG org.eclipse.jetty.util.log - Logging to Logger[org.eclipse.jetty.util.log] via org.eclipse.jetty.util.log.Slf4jLog
14:57:35.099 [Start Level: Equinox Container: 17aab7b4-b3c6-4aab-856f-bfc4da8023bb] INFO org.eclipse.jetty.util.log - Logging initialized @6731ms to org.eclipse.jetty.util.log.Slf4jLog
14:57:35.099 [Start Level: Equinox Container: 17aab7b4-b3c6-4aab-856f-bfc4da8023bb] WARN org.eclipse.jetty.osgi.boot.JettyBootstrapActivator - OSGi support for java.util.ServiceLoader may not be present. You may experience runtime errors.
14:57:35.108 [Start Level: Equinox Container: 17aab7b4-b3c6-4aab-856f-bfc4da8023bb] WARN org.eclipse.jetty.osgi.boot.internal.serverfactory.DefaultJettyAtJettyHomeHelper - No default jetty created.
An error has occurred. See the log file

log file :
[1674050251283.log](https://github.com/b2ihealthcare/snow-owl/files/10447327/1674050251283.log)

Thanks for your help

**Comment by cmark** [comment]
Hi @vachonr,

Snow Owl requires Java 17 or newer. It looks like you are trying to run Snow Owl on Java 13.

```
java.version=13.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
``` 

Could you please upgrade to Java 17 and try again?
Alternatively, you can use our oss [docker image](https://hub.docker.com/r/b2ihealthcare/snow-owl-oss) as well.

I hope this helps.

Cheers,
Mark

**Comment by vachonr** [comment]
Thanks for your answer. It works better but t:he program stop without log file creation.
I copy a  screen shot

***@***.***

De : Mark Czotter ***@***.***>
Envoyé : mercredi 18 janvier 2023 15:38
À : b2ihealthcare/snow-owl ***@***.***>
Cc : VACHON Rene ***@***.***>; Mention ***@***.***>
Objet : Re: [b2ihealthcare/snow-owl] Error launching snow owl (Issue #1102)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi @vachonr<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvachonr&data=05%7C01%7Crene.vachon%40biomerieux.com%7C072fb9b9be9c4f09818008daf96188b8%7Caec0543acc734fa49e2acf52adf9b788%7C0%7C0%7C638096494561421857%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wP9%2B3dVWvCF7D98IyCRwVdwZfLzHP1jKEW8AVZHJB7E%3D&reserved=0>,

Snow Owl requires Java 17 or newer. It looks like you are trying to run Snow Owl on Java 13.

java.version=13.0.1

java.vendor=Oracle Corporation

BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR

Could you please upgrade to Java 17 and try again?
Alternatively, you can use our oss docker image<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhub.docker.com%2Fr%2Fb2ihealthcare%2Fsnow-owl-oss&data=05%7C01%7Crene.vachon%40biomerieux.com%7C072fb9b9be9c4f09818008daf96188b8%7Caec0543acc734fa49e2acf52adf9b788%7C0%7C0%7C638096494561421857%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Uarqtnk5D2ZmkU3Q7bclKL3Z6VJPVv5f%2F3%2FSe4OSXgo%3D&reserved=0> as well.

I hope this helps.

Cheers,
Mark

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fb2ihealthcare%2Fsnow-owl%2Fissues%2F1102%23issuecomment-1387176768&data=05%7C01%7Crene.vachon%40biomerieux.com%7C072fb9b9be9c4f09818008daf96188b8%7Caec0543acc734fa49e2acf52adf9b788%7C0%7C0%7C638096494561421857%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sOQXohbveXWDMOuJ9lkZYOzhSef7ZeWHf7nuSLLThp4%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALB2VV4F4LPL53E4J2YWVDTWS752XANCNFSM6AAAAAAT7E5ZXY&data=05%7C01%7Crene.vachon%40biomerieux.com%7C072fb9b9be9c4f09818008daf96188b8%7Caec0543acc734fa49e2acf52adf9b788%7C0%7C0%7C638096494561421857%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WTEyXGKivYTiLIbzu5G1%2F3Alzlnr2L8d0fFc5zNoVIg%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

AVIS : Ce courrier et ses pieces jointes sont destines a leur seul destinataire et peuvent contenir des informations confidentielles appartenant a bioMerieux. Si vous n'etes pas destinataire, vous etes informe que toute lecture, divulgation, ou reproduction de ce message et des pieces jointes est strictement interdite. Si vous avez recu ce message par erreur merci d'en prevenir l'expediteur et de le detruire, ainsi que ses pieces jointes. NOTICE: This message and attachments are intended only for the use of their addressee and may contain confidential information belonging to bioMerieux. If you are not the intended recipient, you are hereby notified that any reading, dissemination, distribution, or copying of this message, or any attachment, is strictly prohibited. If you have received this message in error, please notify the original sender immediately and delete this message, along with any attachments.

**Comment by vachonr** [comment]
The copy of my screen shot didn't work, I attach a text file :
[console.txt](https://github.com/b2ihealthcare/snow-owl/files/10448972/console.txt)

**Comment by cmark** [comment]
The console log looks fine. If you navigate to http://localhost:8080/snowowl you should see the available REST API endpoints and you should be able to interact with Snow Owl.

If you are planning to import SNOMED CT content, I recommend creating a SNOMED CT Code System first, then importing the content via the RF2 import endpoint. See this page for more details:
Getting Started Guide: https://docs.b2i.sg/snow-owl/index/explore
Import RF2 section: https://docs.b2i.sg/snow-owl/index/explore/import

I hope this helps.

**Comment by vachonr** [comment]
Thanks,

It works but I think I made a mistake, I would like to load this software Help - (b2i.sg)<https://b2i.sg/help/index.jsp>




De : Mark Czotter ***@***.***>
Envoyé : mercredi 18 janvier 2023 20:34
À : b2ihealthcare/snow-owl ***@***.***>
Cc : VACHON Rene ***@***.***>; Mention ***@***.***>
Objet : Re: [b2ihealthcare/snow-owl] Error launching snow owl (Issue #1102)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


The console log looks fine. If you navigate to http://localhost:8080/snowowl you should see the available REST API endpoints and you should be able to interact with Snow Owl.

If you are planning to import SNOMED CT content, I recommend creating a SNOMED CT Code System first, then importing the content via the RF2 import endpoint. See this page for more details:
Getting Started Guide: https://docs.b2i.sg/snow-owl/index/explore<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.b2i.sg%2Fsnow-owl%2Findex%2Fexplore&data=05%7C01%7Crene.vachon%40biomerieux.com%7Cde376d02af4e400ac07708daf98aee15%7Caec0543acc734fa49e2acf52adf9b788%7C0%7C0%7C638096672397136411%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MU4TkIIvhh%2BZuioMVFWOfyUdppwPQ0Gk4SZ%2F%2B6HvBVI%3D&reserved=0>
Import RF2 section: https://docs.b2i.sg/snow-owl/index/explore/import<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.b2i.sg%2Fsnow-owl%2Findex%2Fexplore%2Fimport&data=05%7C01%7Crene.vachon%40biomerieux.com%7Cde376d02af4e400ac07708daf98aee15%7Caec0543acc734fa49e2acf52adf9b788%7C0%7C0%7C638096672397136411%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=h15og8gQLpDlAbgfPRcYZFPGui6W1q381HO2hnK6z6c%3D&reserved=0>

I hope this helps.

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fb2ihealthcare%2Fsnow-owl%2Fissues%2F1102%23issuecomment-1387654354&data=05%7C01%7Crene.vachon%40biomerieux.com%7Cde376d02af4e400ac07708daf98aee15%7Caec0543acc734fa49e2acf52adf9b788%7C0%7C0%7C638096672397292189%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0HyGbwNm%2B5Q28YPNcOA12lZgWZj0E%2FXGVQAkl30dswA%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALB2VVYWMZ5UAV2PRKIWMPTWTBAR7ANCNFSM6AAAAAAT7E5ZXY&data=05%7C01%7Crene.vachon%40biomerieux.com%7Cde376d02af4e400ac07708daf98aee15%7Caec0543acc734fa49e2acf52adf9b788%7C0%7C0%7C638096672397292189%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sQ6fXTi3n2m57JdfPkHROMX3sSvBec8obF7rSUkyX5Q%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

AVIS : Ce courrier et ses pieces jointes sont destines a leur seul destinataire et peuvent contenir des informations confidentielles appartenant a bioMerieux. Si vous n'etes pas destinataire, vous etes informe que toute lecture, divulgation, ou reproduction de ce message et des pieces jointes est strictement interdite. Si vous avez recu ce message par erreur merci d'en prevenir l'expediteur et de le detruire, ainsi que ses pieces jointes. NOTICE: This message and attachments are intended only for the use of their addressee and may contain confidential information belonging to bioMerieux. If you are not the intended recipient, you are hereby notified that any reading, dissemination, distribution, or copying of this message, or any attachment, is strictly prohibited. If you have received this message in error, please notify the original sender immediately and delete this message, along with any attachments.

**Comment by cmark** [comment]
> Thanks, It works but I think I made a mistake, I would like to load this software Help - (b2i.sg)<https://b2i.sg/help/index.jsp> 

That help page belongs to the client application and it was maintained until Snow Owl 5. The newer client documentation is available at https://docs.b2i.sg/snow-owl-client.

Please note that the client application is only available in our Snow Owl Authoring Platform product (this repo is our open source Terminology Server with SNOMED CT support).
For more information please visit: https://b2ihealthcare.com/

**Comment by cmark** [comment]
> Thanks, It works but I think I made a mistake

Also, if you need help with that mistake, do not hesitate to tell us more about it :)
