### ISSUE TITLE
SNOMED CT International Edition import not working

### ISSUE THREAD

**Issue by sudheer-unify-care** [b2ihealthcare/snow-owl#1128]
**Describe the bug**
SNOMED CT International Import is not working

**To Reproduce**
[POST] http://localhost:8082/snowowl/snomedct/SNOMEDCT/import?type=snapshot&createVersions=false

Got 201 response with with Location 
`http://localhost:8082/snowowl/snomedct/SNOMEDCT/import/8c9152ab7592ef33536399ef4405d65434954922`

Error status when checked the status
[GET] http://localhost:8082/snowowl/snomedct/SNOMEDCT/import/8c9152ab7592ef33536399ef4405d65434954922

`
{
    "id": "909f626daf1fbb0e1338d62d0359ae141b034e0a",
    "status": "FAILED",
    "error": {
        "message": "Resource with identifier 'SNOMEDCT' could not be found.",
        "developerMessage": "The requested instance resource (id = 'SNOMEDCT', type = 'Resource') does not exist and/or not yet created.",
        "code": 0,
        "status": 404,
        "additionalInfo": {}
    }
}
`

**Expected behavior**
Able to import the codes

**Version**
 - Snow Owl Version: 8.9.2
 - Elasticsearch Version (external): 7.17.4
 - openjdk version "18.0.2.1" 2022-08-18

I've followed the link for importing https://docs.b2i.sg/snow-owl/index/explore/import

**Comment by cmark** [comment]
Hey @sudheer-unify-care,

That guide misses one API call that creates the SNOMED CT CodeSystem, otherwise the import RF2 call is unable to locate where to put the content.

Please perform this request first, then try the RF2 import as before:

```
POST /codesystems
{
	"id": "SNOMEDCT",
	"url": "http://snomed.info/sct/900000000000207008",
	"title": "SNOMED CT International Edition",
	"language": "en",
	"description": "SNOMED CT International Edition",
	"status": "active",
	"copyright": "© 2022 International Health Terminology Standards Development Organisation 2002-2022. All rights reserved. SNOMED CT® was originally created by the College of American Pathologists. 'SNOMED' and 'SNOMED CT' are registered trademarks of International Health Terminology Standards Development Organisation, trading as SNOMED International. SNOMED CT has been created by combining SNOMED RT and a computer based nomenclature and classification known as Clinical Terms Version 3, formerly known as Read Codes Version 3, which was created on behalf of the UK Department of Health and is Crown copyright. This document forms part of the International Edition release of SNOMED CT® distributed by SNOMED International, which is subject to the SNOMED CT® Affiliate License, details of which may be found at https://www.snomed.org/snomed-ct/get-snomed.",
	"contact": "https://snomed.org",
	"oid": "2.16.840.1.113883.6.96",
	"toolingId": "snomed",
	"settings": {
		"moduleIds": [
			"900000000000207008",
			"900000000000012004"
		],
		"locales": [
			"en-x-900000000000508004",
			"en-x-900000000000509007"
		],
		"languages": [
			{
				"languageTag": "en",
				"languageRefSetIds": [
					"900000000000509007",
					"900000000000508004"
				]
			},
			{
				"languageTag": "en-us",
				"languageRefSetIds": [
					"900000000000509007"
				]
			},
			{
				"languageTag": "en-gb",
				"languageRefSetIds": [
					"900000000000508004"
				]
			}
		],
		"publisher": "SNOMED International",
		"isPublic": true,
		"namespace": "373872000",
		"maintainerType": "SNOMED_INTERNATIONAL"
	}
}
```

This will initialize the CodeSystem and some common settings.
I'll update the guide for the upcoming release.

I hope this helps. Let us know if it succeeded.

Cheers,
Mark

**Comment by sudheer-unify-care** [comment]
@cmark thanks for quick reply, it worked!
