### ISSUE TITLE
Opensearch integration 

### ISSUE THREAD

**Issue by Leanderson-Coelho** [b2ihealthcare/snow-owl#1175]
Does the snow owl work with Opensearch or only with ElasticSearch ?

**Comment by cmark** [comment]
Hi @Leanderson-Coelho,

No, at the moment there is no OpenSearch integration available for Snow Owl. Certain features require more recent (7.10+) Elasticsearch versions, which are not compatible with OpenSearch. For development environments, we recommend using the official Elasticsearch Docker images, while for production environments, we recommend hosted instances either directly via Elastic.co or via AWS/GCE marketplace.

I hope this helps.

Cheers,
Mark

**Comment by Leanderson-Coelho** [comment]
Thank you for the feedback @cmark !
