### ISSUE TITLE
Target Platform is not able to Resolve

### ISSUE THREAD

**Issue by Leanderson-Coelho** [b2ihealthcare/snow-owl#1178]
I'm going through the Development steps and I ended on the 4th step. It seems that it can't be resolved because it is not able to read the following repository:

Unable to read repository at mvn:com.b2international:com.b2international.snomed.ecl.update:2.1.4:zip/content.xml.

So the compile errors are still 
![image](https://github.com/b2ihealthcare/snow-owl/assets/34748960/3e663f48-c4ab-40b6-a9db-9ea552d7d932)

**Comment by cmark** [comment]
Hey @Leanderson-Coelho,

Sorry to hear you run into trouble with the dev env setup. Not sure what went wrong there, we will take a look and get back to you.

What version of Eclipse are you using?

Cheers,
Mark

**Comment by cmark** [comment]
Hey @Leanderson-Coelho,

It looks like that guide is missing a step, we will update it shortly.
Please install the m2e PDE Integration from this site based on your m2e version in your Eclipse installation:
https://download.eclipse.org/technology/m2e/releases/

If you have installed an old Eclipse version, you can try to install this one:
https://archive.eclipse.org/technology/m2e/releases/1.19.0/

I hope this helps.

Cheers,
Mark

**Comment by cmark** [comment]
Also please make sure you have copied the settings.xml from the project's root folder to your `.m2` directory.
https://github.com/b2ihealthcare/snow-owl#maven-settings
