### ISSUE TITLE
snowowl and ES / Opensearch on AWS

### ISSUE THREAD

**Issue by mattecasu** [b2ihealthcare/snow-owl#1202]
There were questions in the past about support for AWS-hosted ES - I would like to know if there was any progress on this.
The last update was that the latest major snowowl (> 8.0.0) needed ES > 7.10. We tried plugging it to the latest OpenSearch (2.7) but it doesn't connect to it.

**Comment by cmark** [comment]
Hi @mattecasu,

We would like to integrate OpenSearch with Snow Owl, which is still on our roadmap. Unfortunately, it gets delayed a bit due to other high-priority items. Hopefully, we will have the time after this year's SNOMED Conference to get our eyes on the OpenSearch integration again and make some progress.

Have you had the chance to spin up your own Elasticsearch instance on AWS? Or try the Elastic.co offering?

Regards,
Mark

**Comment by mattecasu** [comment]
Hi Mark, we noticed that it works with OpenSearch 1.3, but from 1.4 it breaks - we observed for example "request [/locks-lock] contains unrecognized parameter: [include_type_name]" on startup, which would be trivial to solve, but then we stopped because I assume there would be other changes required.

We used the AWS offering only, as that it's our setup: so Elasticsearch 7.10 (which is fine for Snowowl 7.X.X) and Opensearch (which does not work after 1.3).

**Comment by cmark** [comment]
> Hi Mark, we noticed that it works with OpenSearch 1.3, but from 1.4 it breaks - we observed for example "request [/locks-lock] contains unrecognized parameter: [include_type_name]" on startup, which would be trivial to solve, but then we stopped because I assume there would be other changes required.
> 
> We used the AWS offering only, as that it's our setup: so Elasticsearch 7.10 (which is fine for Snowowl 7.X.X) and Opensearch (which does not work after 1.3).

Hi @mattecasu,

It is very unlikely that we will add support for OpenSearch in the coming months/year. If Snow Owl is something you would like to use in the future, I highly recommend using Elasticsearch from the corresponding cloud provider's marketplace. It's easy to set up and connect with Snow Owl.

I'm going to close this issue. Please open a discussion if you have any further queries. 

Regards,
Mark
