### ISSUE TITLE
LOINC Code API Details

### ISSUE THREAD

**Issue by msonowal** [b2ihealthcare/snow-owl#353]
Hi Where can we find the api details of LOINC Codes?

**Comment by cmark** [comment]
Hi @msonowal,

Thank you for your interest in trying out Snow Owl with LOINC.
I'd like to inform you that this repository is for the open source (OSS) part of Snow Owl, which consists of the core modules and SNOMED CT support. 
Support for LOINC and other terminologies is currently under a commercial license and they are not open source.
If you would like to use Snow Owl with these terminologies, feel free to contact us at [info@b2i.sg](mailto:info@b2i.sg).

Regards,
Mark
