### ISSUE TITLE
Loading SNOMED for testing purposes

### ISSUE THREAD

**Issue by dmoka** [b2ihealthcare/snow-owl#377]
Hey B2ihealthcare team,

We are trying to quickly load the SNOMED CT resources into snow-owl version 7 (retrieved using this https://docs.b2i.sg/snow-owl/index/installation) for testing purposes. According to the documentation (https://github.com/b2ihealthcare/snow-owl/blob/7.x/documentation/src/main/markdown/configuration_reference.md) there should be a way to turn of indexing. At part "Component Identifier Configuration" there is a setting with name "source" which can have two possible values: INDEX and MEMORY. The MEMORY setting is not an acceptable configuration so we are wondering if there is another way to achieve this. Could you help us with this issue?

Thanks in advance!

PS: Do you already have a docker file for snow-owl?

**Comment by cmark** [comment]
@mirind4, thank you for your questions.

Not sure exactly which index would you like to turn off?
That configuration reference is for the 6.x version of Snow Owl and it is currently being migrated over to the new https://docs.b2i.sg site.
You can find the available configuration options for that node in this [class](https://github.com/b2ihealthcare/snow-owl/blob/7.x/snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/config/SnomedIdentifierConfiguration.java).

Regarding Snow Owl Docker images:
You can find the current state of the official Snow Owl Docker image in this repository/branch:
https://github.com/b2ihealthcare/snow-owl-docker/tree/7.x

Here is some guidance on how to import an RF2 release into Snow Owl:

To import a SNOMED CT RF2 release after successfully starting Snow Owl Server, you have two options:

1. Use the sctimport console command

Connect to the OSGi console via `telnet localhost 2501` and use the `sctimport rf2_release` command.

Example command to import the SNOMED CT INT Release:
sctimport rf2_release -t SNAPSHOT -b MAIN -v <path to rf2 archive> SNOMEDCT

Replace the <path to rf2 archive> with an actual file path to a local SNOMED CT RF2 release and execute the command.
You can import a FULL release as well, but that will take more time to complete (change the -t argument value to FULL).
The console will ask for a username that will be used as an author for each commit made by the RF2 importer.
You can use any valid username at this point, by default there is a snowowl user available.

The importer will import the SNAPSHOT or FULL content based on your decision (-t argument) to the MAIN branch (-b argument) of the SNOMED CT repository.

2. Use the SNOMED CT Import REST API

Endpoint category is available here: http://localhost:8080/snowowl/snomed-ct/v3/#/imports

First, an RF2 import configuration must be created. This configuration tells Snow Owl how an RF2 release should be treated when importing it into the SNOMED CT index.
Use the `POST /imports` endpoint for that with the following JSON body:

```
{
  "branchPath": "MAIN",
  "codeSystemShortName": "SNOMEDCT",
  "createVersions": true,
  "type": "SNAPSHOT"
}
```

This responds with a `Location` header where you can find the ID for this import configuration.
To start the import, an RF2 file must be uploaded for this configuration via the `POST /imports/:importId/archive` endpoint.
To monitor the import process, you can poll the import via `GET /imports/{importId}`.
The status will change to `COMPLETED` when the import is done.

After successfully importing the SNOMED CT RF2 content, you can use the various SNOMED CT Component APIs to query and/or modify the data.

Hope this helps. Let me know if you have any further questions.

Cheers,
Mark

**Comment by dmoka** [comment]
Hey @cmark,

First and foremost sorry for the late response, I just got back from vacation (from Balaton :) ).

Thanks for your detailed answer! We have picked the second approach you mentioned and we could successfully import SNOMED CT contents. Right now we are learning and investigating the terminology service, following the SNOMED API and SNOMED FHIR Services documentations.

I think the issue can be closed, thanks again for your support.

Üdvözlettel,
mirind4

**Comment by cmark** [comment]
Hi @mirind4,

No worries, thanks for your reply. I hope you have had a great time at Balaton. :)

Glad to hear you have successfully imported your first SNOMED CT content into your Snow Owl instance. May I ask which RF2 Edition/Extension you have imported?

If you have any further questions/issues do not hesitate to contact us.

Üdv.:
Márk

**Comment by dmoka** [comment]
Hi @cmark,

We have imported the SNOMED CT International downloaded from [SNOMED INTERNATIONAL MLDS](https://mlds.ihtsdotools.org/#/landing).

Thanks again for your kind help!
Keep it up!

Üdvözlettel,
Dániel
