### ISSUE TITLE
ES cluster url not being used if set

### ISSUE THREAD

**Issue by caetanopaulo** [b2ihealthcare/snow-owl#378]
Hi,

We are trying to use snow owl with a dedicated ES service.
We set the clusterUrl like so:  

```
repository:
  host: 0.0.0.0
  port: 2036

  index:
    socketTimeout: 60000
    clusterUrl: "http://terminology-elasticsearch-client:9200"
```

We were able to CURL this internal URL (http://terminology-elasticsearch-client:9200) from the snow owl container. But we see this in the logs:

```
 ES REST client is connecting to 'http://127.0.0.1:9200', connect timeout: 1000 ms, socket timeout: 60000 ms. 
```

What are we missing?
Does the ES service has default credentials and it's falling back to the localhost url?

Best Regards

**Comment by cmark** [comment]
@caetanopaulo thank you for your questions!

> What are we missing?

Could you please make sure that the configuration indeed looks like this?
```
repository:
  host: 0.0.0.0
  port: 2036
  index:
    socketTimeout: 60000
    clusterUrl: "http://terminology-elasticsearch-client:9200"
```

> Does the ES service has default credentials and it's falling back to the localhost URL?

No, the ES client does not use any credentials by default. There is no fall back to the localhost URL if you set the `repository.index.clusterUrl` configuration key then Snow Owl's ES client will try to connect to that cluster. 
Also, could you please set the `repository.index.clusterName` to the `cluster.name` of your Elasticsearch Service. The client could fail to connect if this setting is set to the default value (`elastic-snowowl`) and your Elasticsearch Service uses a different value.

Hope this helps,
Mark

**Comment by caetanopaulo** [comment]
Hi Mark!

We changed to configuration file. It looks like this now:

```
repository:
  host: 0.0.0.0
  port: 2036
  index:
    socketTimeout: 60000
    clusterUrl: "http://terminology-elasticsearch-client:9200"
    clusterName: elasticsearch
```
But we are still seeing this in the logs:

```
[2019-07-23T08:10:41.756] INFO  fs-watcher                   org.elasticsearch.http.netty4.Netty4HttpServerTransport          publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200} 
[2019-07-23T08:10:41.894] INFO  fs-watcher                   elastic-snowowl                                                  ES REST client is connecting to 'http://127.0.0.1:9200', connect timeout: 1000 ms, socket timeout: 60000 ms. 
```
Any ideas?

Thanks in advance.

**Comment by cmark** [comment]
Hi @caetanopaulo!

In what kind of environment are you trying to run Snow Owl? Docker? CentOS? Ubuntu?
Also, may I ask how did you install Snow Owl to this machine?

One possible root cause of the issue is that the configuration file you are editing is not the configuration file Snow Owl is actually using on bootstrap.
Snow Owl prints out the following paths at the beginning of the bootstrap phase:
```
Home path: <SO_HOME>\runtime 
Config path: <SO_HOME>\configuration 
Data path: <SO_HOME>\resources 
```

Could you please check that these point to the right locations?
Mark

**Comment by cmark** [comment]
Also, may I ask what version of Snow Owl are you trying to run? Thanks!

**Comment by caetanopaulo** [comment]
Hi Mark,

Here's our context:
We are running this setup on kubernetes:  
- Snowowl: version 7.0.0 we are using the dockerfile from this repo: https://github.com/b2ihealthcare/snow-owl-docker/tree/7.x
- ES: version 1.30.0 

We add the snowowl.yml via a volume mount and we had to change it from /etc/snowowl/snowl.yml to /usr/share/snowowl/configuration/snowowl.yml
(The first one we got from the Dockerfile)

This is how configuration file looks like now:
```
repository:
  host: 0.0.0.0
  port: 2036
  index:
    socketTimeout: 60000
    clusterUrl: "http://terminology-elasticsearch-client:9200"
    clusterName: elasticsearch
```

Now we are getting this exception: 
```
Caused by: java.lang.RuntimeException: Unrecognized field 'clusterName' in config file 'repository'
```

Find the full stack trace in attachment:
[snowowl_exception.log](https://github.com/b2ihealthcare/snow-owl/files/3421262/snowowl_exception.log)

Thanks in advance your awesome support.

**Comment by cmark** [comment]
Yes, mounting the config file should work as you expect, but the Snow Owl RPM package installed by the Dockerfile will try to look up the config file on the `/etc/snowowl/snowowl.yml` path.
See the relevant documentation here:
https://docs.b2i.sg/snow-owl/index-1/index/rpm#directory-layout-of-rpm

It is recommended to mount your configuration file from the local path to the `/etc/snowowl/snowowl.yml` path or change the `SO_CONF_PATH` environment variable to the new default location. NOTE: additional files might need to be placed into this new directory, otherwise Snow Owl will refuse to start or certain modules will not function correctly.

> Now we are getting this exception:

Make sure you use two spaces instead of tabs, otherwise parsing of the configuration file might fail, or nodes will incorrectly be placed under other nodes (in this case clusterName under repository).

Hope this helps,
Mark

**Comment by caetanopaulo** [comment]
Hi Mark,

We are using the yml file in attachment that was also verified by a lint tool.
[snowowl.yml.txt](https://github.com/b2ihealthcare/snow-owl/files/3422412/snowowl.yml.txt)

Note: we are using visual studio code and it deal with tab and spaces pretty well on yml files.
And we are getting the same exception. We tried sorting the clusterName but still no game.

What else can we do?

Thanks!

**Comment by caetanopaulo** [comment]
Hi mark,

We played around with the configuration a bit. We removed the clusterName configuration so that the terminology service will use the default name: "elastic-snowowl" we then changed the name of the ES name to "elastic-snowowl". 

```
curl http://terminology-elasticsearch-client:9200
{
  "name" : "terminology-elasticsearch-client-[ommited]",
  "cluster_name" : "elastic-snowowl",
  "cluster_uuid" : "ANZGb-[ommited]",
  "version" : {
    "number" : "6.7.0",
    "build_flavor" : "oss",
    "build_type" : "docker",
    "build_hash" : "8453f77",
    "build_date" : "2019-03-21T15:32:29.844721Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```
Now we get a java.lang.NullPointerException:
```
org.eclipse.virgo.nano.deployer.api.core.DeploymentException: BundleException
... 
Caused by: org.osgi.framework.BundleException: Exception in com.b2international.snowowl.server.product.ServerProductActivator.start() of bundle com.b2international.snowowl.server.product. 
...
Caused by: com.b2international.snowowl.core.api.SnowowlRuntimeException: com.b2international.snowowl.core.api.SnowowlRuntimeException: Couldn't execute bulk updates 
...
Caused by: com.b2international.snowowl.core.api.SnowowlRuntimeException: Couldn't execute bulk updates 
...
Caused by: com.b2international.index.IndexException: Couldn't execute bulk updates 
...
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException 
...
Caused by: java.lang.NullPointerException 
```

Feels like we are missing something. We are using the default configuration for ES.

Best Regards

**Comment by cmark** [comment]
Yes it looks like the `repository.index.clusterName` has been added recently to the `7.1.0` development version of Snow Owl, so, unfortunately, it is not possible to change that in version `7.0.0`.

Could you please send us the entire log output, it is hard to figure out the exact problem without the actual stack traces?
Thank you,
Mark

**Comment by caetanopaulo** [comment]
Hey Mark,

Here's the full stack trace.
[snowowl_exception_full_1.log](https://github.com/b2ihealthcare/snow-owl/files/3422768/snowowl_exception_full_1.log)

Some configuration context:
- Using the following config on SO_PATH_CONF="/etc/snowowl"
- We changed the ES name to "elastic-snowowl"
- We can curl the http://terminology-elasticsearch-client:9200 from the terminology container

```
repository:
  host: 0.0.0.0
  port: 2036
  index:
    socketTimeout: 60000
    clusterUrl: "http://terminology-elasticsearch-client:9200"
```
We are a bit clueless on what to do next. 

Thanks in Advance :)

**Comment by cmark** [comment]
Hi @caetanopaulo,

Yes, the initial commit has failed due to Elasticsearch bulk update HTTP API inconsistency.
You are using Elasticsearch `6.7.0`, but Snow Owl v7.0.0 was built on top of the Elasticsearch `v6.3.2` HTTP API.
Could you please try again from scratch using Elasticsearch `v6.3.2`?

We are planning to release Snow Owl `v7.1.0` in August, that will hopefully depend on the latest `6.x` Elasticsearch version.

Let me know if you have any further questions, issues!

Cheers,
Mark

**Comment by caetanopaulo** [comment]
Hi Mark!

This worked! 
We are now importing the latest SnomedCT international (SnomedCT_InternationalRF2_PRODUCTION_20190131T120000Z.zip) into our terminology service. 
Hopefully this will work :)

We tried importing the Netherlands version (SnomedCT_Netherlands_EditionRelease_PRODUCTION_20190331T120000Z.zip) first but that did not succeed... we will give it another go if the international import succeeds. 

BTW: We are wondering if you guys know of any terminology server (in the clouds) with the preload SnomedCT international or Netherlands version that we can use for testing?

You rock!
Thanks for all your help!
Best regards!

**Comment by cmark** [comment]
Hi @caetanopaulo,

I'm glad it worked! 😃 

> We tried importing the Netherlands version (SnomedCT_Netherlands_EditionRelease_PRODUCTION_20190331T120000Z.zip) first but that did not succeed... we will give it another go if the international import succeeds.

NRC Extension/Edition releases often contain a bunch of validation errors. Snow Owl logs them under the logger name `import`.

> BTW: We are wondering if you guys know of any terminology server (in the clouds) with the preload SnomedCT international or Netherlands version that we can use for testing?

Do you mean a terminology server as SaaS (like the `Elastic.co` for `Elasticsearch`)? If yes, feel free to contact us at [info@b2i.sg](mailto:info@b2i.sg).

Good luck,
Mark

**Comment by caetanopaulo** [comment]
Hi @cmark,

We ran into a bit of a pickle importing the "SnomedCT_Netherlands_ExtensionRelease_PRODUCTION_20190331T120000Z.zip" package.
It was running almost for 24 hours. The size of the package is approx 41MB.

We checked the logs and we could find some exceptions:
[Snowowl_Import_NL_exceptions.log](https://github.com/b2ihealthcare/snow-owl/files/3434875/Snowowl_Import_NL_exceptions.log)
 ... but we are not sure what to get around this...

Any ideas on what might cause this?

Best Regards

**Comment by cmark** [comment]
Hi @caetanopaulo,

Could you please answer the following questions to help investigate the issue further:
- Which INT RF2 release did you import successfully? Full or Snapshot 20190131?
- Did you restart the server after successfully imported the INT RF2 Release?
- What is the value of the `Xms` and `Xms` Java Heap settings of the Snow Owl process?
- How big is your Elasticsearch cluster? Distribution of node types (data nodes, master nodes, number of shards, number of replicas, etc)?
- How much memory a single Elasticsearch node can use (Xms, Xmx settings in `jvm.options` file)?
- Is there any other custom Elasticsearch configuration you have changed from its default value?

Could you please also share the full log file of the successful INT import and the failed Extension RF2 import?

Thank you,
Mark

**Comment by caetanopaulo** [comment]
Hi @cmark 

> * Which INT RF2 release did you import successfully? Full or Snapshot 20190131?

The latest production extension for NL: SnomedCT_Netherlands_ExtensionRelease_PRODUCTION_20190331T120000Z.zip

We are assuming we do not need to load the full NL edition (SnomedCT_Netherlands_EditionRelease_PRODUCTION_20190331T120000Z.zip) and just the extension (SnomedCT_Netherlands_ExtensionRelease_PRODUCTION_20190331T120000Z.zip) since we already loaded the international SNOMEDCT.

> * Did you restart the server after successfully imported the INT RF2 Release?

I just restarted everything (Terminology and ES) and tried again

> * What is the value of the `Xms` and `Xms` Java Heap settings of the Snow Owl process?

javaOpts: "-Xms8g -Xmx8g" 

> * How big is your Elasticsearch cluster? Distribution of node types (data nodes, master nodes, number of shards, number of replicas, etc)?

- Data Nodes: 2
- Master Nodes: 3
- Number of shards: I think it's the default value.
- Number of replicas: 
    - Data: 2
    - Master: 3

> * How much memory a single Elasticsearch node can use (Xms, Xmx settings in `jvm.options` file)?

Data, master and clients:   heapSize: "1536m"

> * Is there any other custom Elasticsearch configuration you have changed from its default value?

No

> Could you please also share the full log file of the successful INT import and the failed Extension RF2 import?

Since I restarted the pods we lost the full successful import log file. The failed extension one is attached to the previous post. 

Thanks for you help.
Regards

**Comment by cmark** [comment]
Thank you @caetanopaulo!

> We are assuming we do not need to load the full NL edition 

Could you please try to import the latest Snapshot of the NL Extension on top of the `2019-01-31 INT` release?

How did you start the import? Via the OSGi console, or via the REST API?
If you've used the REST API, could you please check the status of your import on the `GET /snowowl/snomed-ct/v3/imports/{importId}` endpoint? It should return `FAILED` status.

I don't have access to that NL Extension RF2 file, unfortunately, but I'll try to reproduce the issue with another Extension RF2.

**Comment by caetanopaulo** [comment]
Hi @cmark 

Restarted all the terminology services last Friday and tried again.
We are trying to import this NL extension in a sub branch from main: 
```
{
  "type": "FULL",
  "branchPath": "MAIN/MAIN-NL"
}
```

The strange thing is that it's now Monday and the import is still running:
```
{
    "type": "FULL",
    "branchPath": "MAIN/MAIN-NL",
    "createVersions": false,
    "codeSystemShortName": "SNOMEDCT",
    "id": "***obfuscated***",
    "status": "RUNNING",
    "startDate": "2019-07-26T14:02:36Z"
}
```

Looking at the Friday logs for import I see this:  [Snowowl_Import_NL_exceptions_0726.log](https://github.com/b2ihealthcare/snow-owl/files/3442588/Snowowl_Import_NL_exceptions_0726.log)

Some "unrecognised RF2 file..." warnings but that's it.    

> Could you please try to import the latest Snapshot of the NL Extension on top of the `2019-01-31 INT` release?

We are trying to import the latest NL production extension package from 31 March 2019: https://mlds.ihtsdotools.org/#/viewReleases/viewRelease/128785


> How did you start the import? Via the OSGi console, or via the REST API?
> If you've used the REST API, could you please check the status of your import on the `GET /snowowl/snomed-ct/v3/imports/{importId}` endpoint? It should return `FAILED` status.

We are using the REST API. That's how we got the "status": "RUNNING".

> I don't have access to that NL Extension RF2 file, unfortunately, but I'll try to reproduce the issue with another Extension RF2.

You can register and get the latest package from here: https://mlds.ihtsdotools.org/#/viewReleases/viewRelease/128785

Best Regards!

**Comment by cmark** [comment]
Hi @caetanopaulo,

> You can register and get the latest package from here: mlds.ihtsdotools.org/#/viewReleases/viewRelease/128785

Thank you! It took a bit of time to get access to the NL extension, but we have been able to download it and already tried to import it on top of the INT 2019-01-31 release.

It looks like there is an issue in the RF2 import time validator that prevents the extension to proceed to the actual import phase. We are investigating the issue and will fix it as soon as possible. It will be available in the `v7.0.1` patch release.

Regards,
Mark

**Comment by cmark** [comment]
Hi @caetanopaulo,

We've successfully resolved your issue and the new v7.0.1 release is available to download at: https://github.com/b2ihealthcare/snow-owl/releases/tag/v7.0.1

After successfully importing the SNOMED CT INT 2019-01-31 release, import the SNAPSHOT of the NL-2019-03-31 release to the desired branch (`MAIN/MAIN-NL`).

How ever, two `StatedRelationship` rows in the NL-2019-03-31 SNAPSHOT (and probably in the FULL as well) release cannot be imported to Snow Owl due to missing destination concept from the `sct2_Concept` file.
The concept ID and the relationship rows are the following:
Concept ID: `39451000146106`
Relationship rows:
```
3876451000146121      20170930        0       11000146104     39461000146109  39451000146106  0       116680003       900000000000010007      900000000000451002
3876481000146127      20170930        0       11000146104     39471000146103  39451000146106  0       116680003       900000000000010007      900000000000451002
```

After removing those two lines from the `StatedRelationship` file the `SNAPSHOT` can be imported into Snow Owl in approx. two minutes.

Let us know if you have successfully imported the NL extension using this new release or have any other issues/questions.

Regards,
Mark

**Comment by caetanopaulo** [comment]
Hi @cmark 

We did what you said and we got were able to get a completed import status.
By looking at the logs we are seeing a lot of "Unrecognized RF2 file" remarks: 
[Snowowl_Import_NL_exceptions_0805.log](https://github.com/b2ihealthcare/snow-owl/files/3468152/Snowowl_Import_NL_exceptions_0805.log)
Not sure if everything was imported successfully... 

By calling the codeSystems endpoint we see this:
```{
    "items": [
        {
            "oid": "2.16.840.1.113883.6.96",
            "name": "SNOMED CT",
            "shortName": "SNOMEDCT",
            "organizationLink": "http://www.snomed.org",
            "primaryLanguage": "ENG",
            "citation": "SNOMED CT contributes to the improvement of patient care by underpinning the development of Electronic Health Records that record clinical information in ways that enable meaning-based retrieval. This provides effective access to information required for decision support and consistent reporting and analysis. Patients benefit from the use of SNOMED CT because it improves the recording of EHR information and facilitates better communication, leading to improvements in the quality of care.",
            "branchPath": "MAIN",
            "iconPath": "icons/snomed.png",
            "terminologyId": "com.b2international.snowowl.terminology.snomed",
            "repositoryUuid": "snomedStore"
        }
    ]
}```

If we do a count on concepts:
- Before the import: 466612
- After the import: 473649

If we look at the branch state, we get a "FORWARD":
```{
            "metadata": {},
            "name": "MAIN-FULL-NL",
            "baseTimestamp": 1564651174609,
            "headTimestamp": 1565005535199,
            "state": "FORWARD",
            "deleted": false,
            "path": "MAIN/MAIN-FULL-NL"
        }
```
Is this the way it's supposed to be?

Now the problem we are having is that we want to query for the Dutch translations for a concept.
For that we using this call:

```
curl -X GET \
  http://**terminology url**/snowowl/snomed-ct/v3/browser/MAIN/MAIN-FULL-NL/concepts/160573003 \
  -H 'Accept-Language: nl-NL;q=0.9,en-US;q=0.1' \
  -H 'Authorization: Basic **obsfuscated**' \
  -H 'Host: **terminology url**' \
```

But we get all the NL and EN translations. Is there a better way to achieve this? (sorry for the noob questions)? 

Best Regards

**Comment by cmark** [comment]
Hi @caetanopaulo,

I'm glad to hear you have been able to import the NL extension.

Not sure about why it is printing the `Unrecognized RF2 file` warning messages. 
Did you specify the `FULL` or the `SNAPSHOT` RF2 release type in the import configuration?

How the header of this RF2 file looks like?
__MACOSX/SnomedCT_Netherlands_ExtensionRelease_PRODUCTION_20190331T120000Z_Patched/Full/Refset/Content/._der2_Refset_SimpleFull_NL_20190331.txt

The code system looks okay and the branch state as well since you have made commits to that branch.

> But we get all the NL and EN translations. Is there a better way to achieve this? (sorry for the noob questions)?

To query a specific language reference set (in this case the NL Lang RefSet), you need to use the special `Accept-Language` format to identify language reference sets outside the currently mapped language codes.
The currently mapped lang. refsets are: `en-gb`, `en-us`, `en-sg`, `en-au`, `es`.
To query unmapped language refsets use the following syntax:
- `Accept-Language: en-x-<language_refset_id>;q=0.9,en-US;q=0.1`

Let me know if this works for you,
Mark

**Comment by caetanopaulo** [comment]
Hi @cmark 

> Did you specify the `FULL` or the `SNAPSHOT` RF2 release type in the import configuration?

FULL. 

> How the header of this RF2 file looks like?
> __MACOSX/SnomedCT_Netherlands_ExtensionRelease_PRODUCTION_20190331T120000Z_Patched/Full/Refset/Content/._der2_Refset_SimpleFull_NL_20190331.txt

```
id	effectiveTime	active	moduleId	refsetId	referencedComponentId
015eca8c-600b-4b33-bf55-1f74efe41bef	20150916	1	11000146104	8721000146106	162278001
03a531ef-d275-4713-9e70-8c08acecd8f2	20150916	1	11000146104	2551000146109	709489006
...
```

> To query a specific language reference set (in this case the NL Lang RefSet), you need to use the special `Accept-Language` format to identify language reference sets outside the currently mapped language codes.
> The currently mapped lang. refsets are: `en-gb`, `en-us`, `en-sg`, `en-au`, `es`.
> To query unmapped language refsets use the following syntax:
> 
> * `Accept-Language: en-x-<language_refset_id>;q=0.9,en-US;q=0.1`

This worked :) 
BTW. Is there anyway we can get descriptions for concepts in a batch call (multiple concepts IDs in one call)?

We also getting a HTTP 500 when we try to call the /CodeSystem endpoint:

```
curl -X GET \
  http://**OBFUSCATED**/snowowl/fhir/CodeSystem \
  -H 'Accept: */*' \ 
  -H 'Authorization: Basic **OBFUSCATED**' \
  -H 'Host: **OBFUSCATED**' \
```
Here are the logs: 
[Snowowl_CodeSystem_Endpoint_exceptions_0806.log](https://github.com/b2ihealthcare/snow-owl/files/3471112/Snowowl_CodeSystem_Endpoint_exceptions_0806.log)
 
Thanks for your help!
Best Regards

**Comment by cmark** [comment]
Hi @caetanopaulo,

> How the header of this RF2 file looks like?

These files are MacOS metadata files, you can safely ignore them. More info at: https://apple.stackexchange.com/questions/14980/why-are-dot-underscore-files-created-and-how-can-i-avoid-them

> BTW. Is there anyway we can get descriptions for concepts in a batch call (multiple concepts IDs in one call)?

You can use the `ecl` filter on the `GET /:path/concepts` for that, like this:

```
ecl: ID1 OR ID2 OR ID3 ... OR IDN
```

From the next v7.1.0 release, there will be a new `id` filter on this very same endpoint and also a new `POST` based `/search` endpoint when the URL would be too long for the desired request.

> We also getting a HTTP 500 when we try to call the /CodeSystem endpoint:

We will investigate this issue and get back to you.

Regards,
Mark

**Comment by caetanopaulo** [comment]
Hi @cmark 

The filtering works well :)

Are there any plans to include n-NL as a mapped language in future releases?

Thanks!

**Comment by cmark** [comment]
Hi @caetanopaulo,

Glad to hear filtering works well. :)

> Are there any plans to include n-NL as a mapped language in future releases?

Yes, we are planning to include some kind of configuration option (`snomed.acceptLanguages`) to map certain language reference set IDs to their corresponding language codes.

Let me know if you have any further questions.
Cheers,
Mark

**Comment by cmark** [comment]
Hi @caetanopaulo,

Just to let you know, the new 7.1.0 release is out.
There is a new configuration option (`snomed.languages`) to configure additional languageCode + languageRefSet options. 

This is the default configuration value:

```
snomed:
  languages:
    -
      code: en
      refSetIds: ["900000000000509007", "900000000000508004"]
    -
      code: en-us
      refSetIds: ["900000000000509007"]
    -
      code: en-gb
      refSetIds: ["900000000000508004"]
```
You can add yours as new item to the end of the languages list:
```
snomed:
  languages:
    -
      code: en
      refSetIds: ["900000000000509007", "900000000000508004"]
    -
      code: en-us
      refSetIds: ["900000000000509007"]
    -
      code: en-gb
      refSetIds: ["900000000000508004"]
    -
      code: nl-NL
      refSetIds: ["<NL Language RefSet ID>"]
```

Regards,
Mark
