### ISSUE TITLE
CONFIG_AREA is set incorrect in windows snowowl.bat

### ISSUE THREAD

**Issue by dolchchr** [b2ihealthcare/snow-owl#395]
Affected is the file snowowl.bat of the windows release from https://github.com/b2ihealthcare/snow-owl/releases/download/v7.1.0/snow-owl-oss-7.1.0.zip

the CONFIG_AREA is set by
set CONFIG_AREA=%KERNEL_HOME%/work 
to 'Volume:\path_to_folder\snowowl_folder \work'
what leads to the error:

"<title>Invalid Configuration Location</title>The configuration area at ''Volume:\path_to_folder\snowowl_folder \work' could not be created.  Please choose a writable location using the '-configuration' command line option."

The correct path must be without blank:
set CONFIG_AREA=Volume:\path_to_folder\snowowl_folder\work

**Comment by cmark** [comment]
Hi @dolchchr,

Thank you for reporting the problem.
This is indeed an issue and affects the zip packages and the Windows startup script.

A workaround to resolve the issue locally is to remove the extra space from the end of this line:
```
  for %%I in ("%SCRIPT_DIR%..") do set KERNEL_HOME=%%~fsI 
```

After that Snow Owl will start properly. 

Hope this helps.
Cheers,
Mark
