### ISSUE TITLE
Support for capability statement

### ISSUE THREAD

**Issue by psiotwo** [b2ihealthcare/snow-owl#416]
Would be great to expose capability statement on /metadata endpoint (TerminologyCapabilities), as specified in http://hl7.org/fhir/http.html.

**Comment by cmark** [comment]
Hi @psiotwo,

Indeed, that would be really great addition to the FHIR API, definitely on our radar.

Cheers,
Mark

**Comment by cmark** [comment]
Hi @psiotwo,

It's been a while. I just want to let you know that the `/metadata` endpoint is now available in the latest [8.0.0](https://github.com/b2ihealthcare/snow-owl/releases/tag/v8.0.0) release.

Cheers,
Mark
