### ISSUE TITLE
Import of SNOMED UK extensions failed

### ISSUE THREAD

**Issue by psiotwo** [b2ihealthcare/snow-owl#417]
I tried to 
1) create a branch for SNOMED UK
```
{
  "parent": "MAIN",
  "name": "SNOMEDCT-UK"
}
```
2) create SNOMED CT UK codesystem
```
{
  "oid": "1",
  "branchPath": "MAIN/SNOMEDCT-UK",
  "extensionOf": "SNOMEDCT",
  "name": "SNOMED CT UK Clinical Edition",
  "organizationLink": "http://digital.nhs.uk",
  "primaryLanguage": "ENG",
  "repositoryUuid": "snomedStore",
   "citation": "SNOMED CT UK Clinical Edition",
  "iconPath": "icons/snomed.png",
  "shortName": "SNOMEDCT-UK",
  "terminologyId": "com.b2international.snowowl.terminology.snomedctuk"
}
```
3) import Snomed UK Clinical Edition (20191001), in a similar manner as for SNOMED CT, but the import failed (after 15 mins). Logs in https://pastebin.com/5eeskrYD.

Cannot spot any exception inside, but there are some ERRORs of not found mappings. 

Any idea would be appreciated.

Cheers,
Petr

**Comment by cmark** [comment]
Hi @psiotwo,

1. Branch creation looks okay.
2. Creating a new code system is almost okay, the `terminologyId` is actually a constant ID for ALL SNOMED CT related terminologies (it is more like a `toolingId`, than an identifier of the terminology itself, we might rename it in the future), use this for all SNOMED CT code systems: `com.b2international.snowowl.terminology.snomed`
3. Looks like that UK Clinical RF2 requires additional content to be imported first, see lines:
```
Component refers to a non-existing concept with id '7800211000001106' in effective time '2019-10-01' 
Component refers to a non-existing concept with id '28191311000001105' in effective time '2019-10-01' 
Component refers to a non-existing concept with id '33503811000001105' in effective time '2019-10-01' 
Component refers to a non-existing concept with id '17090911000001103' in effective time '2019-10-01' 
Component refers to a non-existing concept with id '29128911000001105' in effective time '2019-10-01' 
```
For example, the concept `7800211000001106` is not present at all neither in the given UK Clinical RF2 and neither in the currently imported SNOMED CT content.
It's worth reporting it to NHS Digital, they may know what content is required before you can import this RF2 (or there is an error in the new RF2 release).

Usually, when something like this happens we will try to find the problematic rows in the RF2 and remove them so at least we can import the release partially. And by doing that you also get the erroneous rows that you can report back to NHS Digital.
To do that you can use a tool like this:
https://github.com/b2ihealthcare/rf2-d2

Let me know if you have any further questions or issues.

Cheers,
Mark

**Comment by psiotwo** [comment]
Hi @cmark,

thanks for hint. I was able to import SNOMEDCT-UK after removing der2_Refset_SimpleFull_GB1000000_20190601.txt and der2_iisssciRefset_ExtendedMapFull_GB1000000_20190601.txt
from the distribution.

Bests,
Petr

**Comment by cmark** [comment]
Resolved. Closing issue.
