### ISSUE TITLE
How to use other terminologies with SnowOwl?

### ISSUE THREAD

**Issue by psiotwo** [b2ihealthcare/snow-owl#418]
I am interested to find out what would be the best way to import non-SNOMED terminologies to SnowOwl, either existing ones (e.g. LOINC), or custom ones. What would be the entry point in source code for developing a custom store for other terminologies?

**Comment by cmark** [comment]
Hi @psiotwo,

Thank you for your interest in using Snow Owl for non-SNOMED terminologies.

The current OSS version includes the terminology server core architecture and the SNOMED CT plug-ins. On top of that B2i Healthcare provides support for many terminologies (including ATC, ICD-10, LOINC, custom local codes), intensional, extensional value sets, mapping sets and an Authoring Environment, where authors can maintain new versions of their terminologies, value sets, mappings, etc. in a simple, easy to use user interface.
Feel free to contact us at [info@b2i.sg](mailto:info@b2i.sg) for exact details and pricing options.

Regards,
Mark

**Comment by cmark** [comment]
Resolved issue. Closing.
