### ISSUE TITLE
How to set up ELK reasoner with SnowOwl 7.2.0

### ISSUE THREAD

**Issue by psiotwo** [b2ihealthcare/snow-owl#421]
Hi,
after running latest docker image 7.x, I can only see NoOpReasoner in the list of /snomed-ct/v3/reasoners. Is classification supported in OSS version? If so, how to plug e.g. ElkReasoner in?
Thanks,
Petr

**Comment by cmark** [comment]
Hi @psiotwo,

Yes, it is supported and this is a bug if that's not the case. 
I've fixed it, it should be included in the new `7.x` OSS image.

Regards,
Mark

**Comment by psiotwo** [comment]
Hi @cmark ,
I confirm it works.
Thanks,
Petr
