### ISSUE TITLE
Get refsets endpoint returns 500

### ISSUE THREAD

**Issue by psiotwo** [b2ihealthcare/snow-owl#422]
Hi,

tried to get all SNOMED refsets from SnowOwl and ended up with running GET /snowowl/snomed-ct/v3/MAIN/refsets?limit=10 (also tried /snowowl/snomed-ct/v3/MAIN/900000000000455006/refsets?limit=10) - both return 500 (stacktrace https://pastebin.com/RhnazQvp).

Petr

**Comment by cmark** [comment]
Hi @psiotwo,

Thank you for reporting the issue. That looks like a bug in the REST API controller.
I'll fix it and a new docker image will be available with the fix in an hour or so. 

Regards,
Mark

**Comment by psiotwo** [comment]
Hi @cmark,
thanks for quick response. Tried latest docker 'b2ihealthcare/snow-owl-oss:7.x' just now and looks like it behaves the same as before ... (also Swagger docs still suggests that  refSetTypes is a path variable).
Petr

**Comment by cmark** [comment]
Hi @psiotwo,

Yeah, there was a build failure, unfortunately. Please try again in 20-30 minutes.

Regards,
Mark
