### ISSUE TITLE
Version control example

### ISSUE THREAD

**Issue by joshlk** [b2ihealthcare/snow-owl#425]
Hi,

I'm working with @psiotwo and exploring the branching and version control capabilities of Snow Owl. I am doing a test whereby I create a new branch, make a change and then merge that change with the original branch.

Here is what I've got so far:
1. Create a new branch "test-1" (branched from MAIN) `/snowowl/snomed-ct/v3/branches`:
```
curl -X POST "http://X:8080/snowowl/snomed-ct/v3/branches" -H "accept: application/json;charset=UTF-8" -H "authorization: Basic X" -H "Content-Type: application/json" -d "{ \"parent\": \"MAIN\", \"name\": \"test-1\", \"metadata\": { }}"
```

2. Delete a concept on that branch (449752001) `/snowowl/snomed-ct/v3/MAIN%2Ftest-1/concepts/449752001`:
```
curl -X DELETE "http://X:8080/snowowl/snomed-ct/v3/MAIN%2Ftest-1/concepts/449752001?force=true" -H "accept: */*" -H "authorization: Basic X"
```

Now if I compare the two branches using `/snowowl/snomed-ct/v3/compare`:
```
curl -X POST "http://X:8080/snowowl/snomed-ct/v3/compare" -H "accept: application/json;charset=UTF-8" -H "authorization: Basic X" -H "Content-Type: application/json;charset=UTF-8" -d "{ \"baseBranch\": \"MAIN\", \"compareBranch\": \"MAIN/test-1\", \"limit\": 0}"
```
It shows no changes:
```
{
  "baseBranch": "MAIN",
  "compareBranch": "MAIN/test-1",
  "compareHeadTimestamp": 1573640436578,
  "newComponents": [],
  "changedComponents": [],
  "deletedComponents": [],
  "totalNew": 0,
  "totalChanged": 0,
  "totalDeleted": 0
}
```

Do I need to commit the change before I can see changes? What am I missing?

**Comment by cmark** [comment]
Hi @joshlk,

You did everything perfectly and this is how the API is intended to be used.
How ever, there was an issue in the code that initialized the identifier of the newly created branch incorrectly, which results in empty compare data.
A new docker image will be up soon (30 mins or so) on DockerHub with the `7.x` tag which you can try out.
Make sure to create another branch from scratch and repeat the delete + compare steps.

Let us know if that worked for you.

Cheers,
Mark

**Comment by joshlk** [comment]
This works in the latest version 👍

**Comment by cmark** [comment]
Awesome, thank you for checking and getting back to me.
