### ISSUE TITLE
ECL support

### ISSUE THREAD

**Issue by joshlk** [b2ihealthcare/snow-owl#427]
Hi,

I'm investigating Snow Owl's support of SNOMED ECL (Expression Constraint Language). In the frontpage [readme](https://github.com/b2ihealthcare/snow-owl/blob/277bf10eafa71f7ea7d0a203f18830d40c92e420/README.md) it states that you support ECL 1.3.

It also looks like the best way of querying using ECL is using the `/snomed-ct/v3/{path}/concepts` endpoint with the `ecl` parameter.

How is the ECL executed? What engine or reasoner does it use? Are all ECL 1.3 operations fully supported?

Thanks,
Josh

**Comment by cmark** [comment]
Hi @joshlk,

Yes, Snow Owl does support all operations described in the ECL v1.3 spec (https://confluence.ihtsdotools.org/display/DOCECL). 

Execution logic:
When you filter concepts by the `ecl` it will execute the following steps:
1. Parses the ECL expression and returns back with HTTP 400 in case of a Syntax error
2. Evaluates the ECL expression using a series of Elasticsearch search queries against the current indexes. In detail, it searches for SNOMED CT concept, relationship and member documents depending on the given ECL structure.
3. Appends the evaluated ECL expression as an additional filter to the final concept search, where it will be combined with any other filter you've specified in your HTTP request. For example, if you specify both `ecl` and `module` query parameters, it will return concepts that match that ECL expression from that module.

It does not use any special evaluation engines, just the search engine functionality provided by Elasticsearch.

Let me know if you have any further questions.

Cheers,
Mark

**Comment by cmark** [comment]
Resolved issue. Closing.
