### ISSUE TITLE
not authenticated health check (aka readinessProbe) endpoint *without* authentication

### ISSUE THREAD

**Issue by martinmart92** [b2ihealthcare/snow-owl#430]
hi! I understand `/snowowl/admin/info` endpoint is the preferred health check endpoint as described in https://docs.b2i.sg/snow-owl/index/explore/check-status

While trying to deploy snowowl in kubernetes, I am struggling configuring kubernetes health configuration, since snowowl returns a HTTP 401 `Missing authorization token` when called without authentication. I am referring to readinessProbe defined here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

Could it be possible to have a non restricted endpoint for such simple usage? I would basically need a very simple endpoint that returns 200 when the application is ready to receive traffic, or other error code otherwise.
Thank you!
Some detail of my test with docker image `b2ihealthcare/snow-owl-oss:7.x`
```
curl --verbose http://localhost:8080/snowowl/admin/info
* About to connect() to localhost port 8080 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /snowowl/admin/info HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8080
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json;charset=utf-8
< X-Content-Type-Options: nosniff
< Transfer-Encoding: chunked
< Server: Jetty(9.4.18.v20190429)
< 
* Connection #0 to host localhost left intact
{"status":401,"code":0,"message":"Missing authorization token","developerMessage":"Missing authorization token","errorCode":0,"statusCode":401}

```

**Comment by cmark** [comment]
Hi @martinmart92,

Well, if you only care about the actual availability of the services, then you could just ping the base URL `http://localhost:8080/snowowl`, which returns the API documentation site.
If that is up and returns `HTTP 200` then you can be sure that the services are ready to receive requests.

I hope this works for you.

In the meantime, we will consider removing authorization for the health check endpoint and include that change in the upcoming 7.2.0 release.

Regards,
Mark

**Comment by martinmart92** [comment]
thanks @cmark for your answer! It works for me. 
`curl http://localhost:8080/snowowl/` worked (removing the final `/` returned a 302, but including it returned a 200)

I will close this issue. Have a good day!
