### ISSUE TITLE
Creation of a concept

### ISSUE THREAD

**Issue by psiotwo** [b2ihealthcare/snow-owl#434]
I am trying to create a new concept. Steps I have taken:

1. Successfully imported SNOMED CT Intl 20190131 and SNOMED UK 20180131

2. Created a custom branch as a child of SNOMED CT Intl
POST `/snowowl/snomed-ct/v3/branches`
```
{
  "parent": "MAIN",
  "name": "TEST"
}
```

3. POST `/snowowl/cis/login`
```
{
  "username": "snowowl",
  "password": "snowowl"
}

```

4. POST `/snowowl/cis/authenticate` - and I obtained the token which I use in the subsequent requests

5. Generate and publish an identifier - I am using a fake namespace 1009999.
POST `/snowowl/cis/sct/generate?token=XYZ`, 
PUT `/snowowl/cis/sct/publish?token=XYZ`, 

6. Create a fresh concept POST `/snowowl/snomed-ct/v3/MAIN/TEST/concepts. The ids 11009999102, 21009999106, 31009999108, 41009999101 were generated and published in point 5.

```{
  "active": true,
  "commitComment": "First concept first commit message",
  "defaultModuleId": "900000000000207008",
  "descriptions": [
    {
      "acceptability": {
          "900000000000509007": "PREFERRED",
          "900000000000508004": "PREFERRED"
      },
      "active": true,
      "caseSignificance": "ENTIRE_TERM_CASE_SENSITIVE",
      "conceptId": "11009999102",
      "id": "41009999101",
      "languageCode": "en",
      "moduleId": "900000000000207008",
      "namespaceId": "1009999",
      "term": "First Concept - PT",
      "typeId": "900000000000013009"
    },
        {
      "acceptability": {
          "900000000000509007": "PREFERRED",
          "900000000000508004": "PREFERRED"
      },
      "active": true,
      "caseSignificance": "ENTIRE_TERM_CASE_SENSITIVE",
      "conceptId": "11009999102",
      "id": "31009999108",
      "languageCode": "en",
      "moduleId": "900000000000207008",
      "namespaceId": "1009999",
      "term": "First Concept - FSN",
      "typeId": "900000000000003001"
    }
  ],
  "relationships" : [
     {
      "active": true,
      "id": "21009999106",
      "moduleId": "900000000000207008",
      "namespaceId": "1009999",
      "destinationId":"138875005",
      "typeId": "116680003"
    }
  ],
  "id": "11009999102",
  "moduleId": "900000000000207008",
  "namespaceId": "1009999"
}

```

As an output I get

```{
    "status": 400,
    "code": 0,
    "message": "Cannot register 1 component IDs because they are not available, reserved, or already assigned.",
    "developerMessage": "Input representation syntax or validation errors. Check input values.",
    "errorCode": 0,
    "statusCode": 400,
    "11009999102": "Published"
}

```

The log is silent - after concept creation request  it outputs just 

```
[2019-11-18T15:22:25.416] INFO  eventbus-128                                     request                                                          {"commitComment":"First concept first commit message","next":{"active":true,"moduleId":"900000000000207008","operation":"browse","type":"SnomedConceptCreateRequest"},"type":"TransactionalRequest","branchPath":"MAIN/TEST","repositoryId":"snomedStore"} ```

What I am missing?

Thanks,

Petr

**Comment by cmark** [comment]
Hi @psiotwo,

Looks almost right, just a small problem, you have generated concept IDs for both of your descriptions and your relationship.
The IDs `1009999106, 31009999108, 41009999101` represent concept IDs and the API fails to recognize them as valid description and relationship IDs and it cannot register the ID, because we ask to register it as a description/relationship ID.
Two options to solve your issue:
1. Generate descriptions with partitionId `11` and relationships with partitionId `12`.
2. You can use the `namespaceId` property of the Concept Create endpoint to generate the IDs on the fly when you create the concept and not before you invoke the API (this is true for all SNOMED CT Component create endpoints). You already specify it in your JSON input so feel free to omit the `id` property completely.

Let me know if this works for you.

Cheers,
Mark

**Comment by apeteri** [comment]
One other issue is that a Published SCTID can not be used when creating new components - this state represents identifiers which are already a part of an RF2 dataset made available to terminology content consumers. This is what the 400 response referred to.

Refer to this diagram for the lifecycle of a single SCTID:

![sctid_states](https://user-images.githubusercontent.com/1411829/69071365-0f4f9780-0a2a-11ea-84fb-969c77094b0b.png)

Regards,
András

**Comment by psiotwo** [comment]
Hi @cmark and @apeteri , thanks for really helpful comments. (2 worked for me)

**Comment by cmark** [comment]
Resolved issue. Closing.
