### ISSUE TITLE
How to use FHIR $translate endpoint 

### ISSUE THREAD

**Issue by psiotwo** [b2ihealthcare/snow-owl#435]
Trying to use a ConceptMap/$translate endpoint on the following map (obtained by `GET /fhir/ConceptMap/snomedStore:MAIN/2019-07-31:446608001` in my SnowOwl runtime)

```
{
    "resourceType": "ConceptMap",
    "id": "snomedStore:MAIN/2019-07-31:446608001",
    "language": "en-us",
    "url": "http://snomed.info/sct/version/20190731",
    "identifier": {
        "use": "official",
        "system": "http://snomed.info/sct/version/20190731",
        "value": "446608001"
    },
    "version": "2019-07-31",
    "name": "ICD-O simple map reference set",
    "title": "ICD-O simple map reference set",
    "status": "active",
    "date": "2019-07-31T00:00:00.000+0000",
    "group": [
        {
            "source": "http://snomed.info/sct",
            "sourceVersion": "20190731",
            "target": "uri://unknown_target_codesystem",
            "element": [
                {
                    "code": "173604004",
                    "display": "Entire interarytenoid notch",
                    "target": [
                        {
                            "code": "C32.0",
                            "equivalence": "equivalent"
                        }
                    ]
                },
 ...
```

The request I use is `GET /fhir/ConceptMap/$translate?code=173604004&system=http://snomed.info/sct&targetsystem=uri://unknown_target_codesystem`

As an outcome I get

```
{
    "resourceType": "Parameters",
    "parameter": [
        {
            "name": "result",
            "valueBoolean": false
        },
        {
            "name": "message",
            "valueString": "0 match(es)."
        }
    ]
}
```

So I suspect, maybe the target codesystems of all SNOMED maps need to be created before SNOMED import takes place to avoid the weird `uri://unknown_target_codesystem` IRIs?

Still, I would expect the above query to return the mapping (even with weird IRI) ...

Thanks,
Petr

**Comment by cmark** [comment]
Hi @psiotwo,

The `$translate` operation has been refactored and reimplemented in the latest [8.0.0](https://github.com/b2ihealthcare/snow-owl/releases/tag/v8.0.0) release. Feel free to try it out and reopen this ticket if you still find issues around it.

Cheers,
Mark
