### ISSUE TITLE
Auth question

### ISSUE THREAD

**Issue by ivelina-yordanova** [b2ihealthcare/snow-owl#437]
Hi,

I see you have two identityProviders at the moment. Do you have it as a goal somewhere on your roadmap to support OAuth? 

From what I am seeing and I think adding it wouldn't be as straightforward as just adding a new plugin because you use internal/custom jwt creator and validator in the identity plugin so it looks like adding new provider would require changing this and essentially create a slightly diff version, which is not ideal.

Thanks

**Comment by ivelina-yordanova** [comment]
Hi,

Sorry about that closed it by mistake.

I was looking at the ldap setup instructions and was wondering if there you can give some example of setup for the three files `permissions.ldif`, `roles.ldif`, `pm.ldif`?

The descriptions is detailed but I am trying to use okta interface and not pure openLdap, because we want to avoid it and that makes it a bit tricky.

Thanks

**Comment by ivelina-yordanova** [comment]
Hi again,

Is there a way to get that example please?

Thanks

**Comment by cmark** [comment]
Hi @ivelina-yordanova,

Sorry for my late reply.

> I see you have two identityProviders at the moment. Do you have it as a goal somewhere on your roadmap to support OAuth?

The current JWT token implementation is brand new and supports the `file` and `ldap` use cases at the moment. We will implement and improve on that in the near future, that is definitely on our radar. 
You could how ever implement your own `IdentityProvider` that supports an external OAuth system.
Just make sure you override the [IdentityProvider.auth()](https://github.com/b2ihealthcare/snow-owl/blob/7.x/core/com.b2international.snowowl.identity/src/com/b2international/snowowl/identity/IdentityProvider.java#L141) method and implement your own token verification algorithm.
If you only care about authentication and not about authorization then you can return a `User` instance with the [Administrator](https://github.com/b2ihealthcare/snow-owl/blob/7.x/core/com.b2international.snowowl.identity/src/com/b2international/snowowl/identity/domain/Role.java#L32) role.

Not sure if you actually need those ldif files in this case, you can implement your own schema and use it in your identity provider.

Let me know if you have further questions.

Cheers,
Mark

**Comment by cmark** [comment]
Hi @ivelina-yordanova,

Feel free to reopen this ticket if you have any further questions.
Closing.

Cheers,
Mark
