### ISSUE TITLE
Uploading CodeSystems, ConceptMaps and ValueSets

### ISSUE THREAD

**Issue by ivelina-yordanova** [b2ihealthcare/snow-owl#440]
Hi,

I was looking at the documentation and the code and iI have a hard time figuring out how to upload new ConceptMaps, CodeSystems and ValueSets.

Theoretically it should be possible to server all these :
* CodeSystems - https://www.hl7.org/fhir/terminologies-systems.html 
* ConceptMaps - https://www.hl7.org/fhir/terminologies-conceptmaps.html 
* ValueSets - https://www.hl7.org/fhir/terminologies-valuesets.html
through the FHIR API, but there is not such option in the REST API in the current version of snowowl for that.

For the CodeSystems there's an admin API and from what I understand requires to  create a separate branch, repository, the code system and the import the data through the commands in the readme. Is this correct?
I also am not completely clear on is how this then gets served by the FHIR API?
In the commercial version you have LOINC and few others, are those separate branches that then the FHIR API pulls when GETting the codeSystems? Doesn’t that make them essentially extensions and you said the lookup from an extension is something you are adding now?

Also how does the upload of ValueSets and ConceptMaps works at the moment and would there be a REST API for this?  

Those are a lot of questions fired at once sorry, hopefully it's clear enough though.

Thanks

**Comment by ivelina-yordanova** [comment]
Maybe the better way of asking this is 

1) What is (if there is one) the recommended way of modelling and adding code systems so that the performance is not hindered or the functionality. 
Should each CodeSystem be a separate unmerged branch, i.e like an extension to the Snomed one or whould they each have their own repo and MAIN branch with their own extensions, versioning etc? Or is there a completely different option?

2) Would it possible to do that through the REST API? (also for the ValueSets and CodeMappings)

**Comment by cmark** [comment]
Hi @ivelina-yordanova,

The Snow Owl Terminology Server supports collaborative authoring for Code Systems, Mapping Sets and Value Sets via either our dedicated Snow Owl Authoring Client or a custom solution using our Java or REST API.  
For generic Value Sets, Mapping Sets and Local Code Systems, you can take a look at a short video at https://www.youtube.com/watch?v=TsgJUGCY0dg. 

These artifacts along with the rest of the supported terminologies are served via the standard FHIR API as FHIR Code Systems, Value Sets and Concept Maps. No update, create or delete operations are supported via the FHIR API.  Eventually, we _could_ support the full CRUD operations for our Local Code Systems, Value Sets and Mapping Sets via the FHIR API, but given our dedicated solution for sophisticated authoring it has not been a high-priority so far.

> In the commercial version you have LOINC and few others, are those separate branches that then the FHIR API pulls when GETting the codeSystems? Doesn’t that make them essentially extensions and you said the lookup from an extension is something you are adding now?

Each code system resides on a dedicated repository capable of revision controlled authoring. Dependent extensions are only required for SNOMED CT, hence the rest of the code systems, value sets and mapping sets can be served via the FHIR API without the current on-going extension effort.

> What is (if there is one) the recommended way of modelling and adding code systems so that the performance is not hindered or the functionality.
Should each CodeSystem be a separate unmerged branch, i.e like an extension to the Snomed one or whould they each have their own repo and MAIN branch with their own extensions, versioning etc.? Or is there a completely different option?

It depends on the use case and the structure of the CodeSystem.
For example, SNOMED CT can be modeled and stored as separate "CodeSystems" without dependencies between each other living on unmerged branches (the MAIN aka master branch is completely empty, just the necessary metadata that actually lives there).
The other way that is a possible approach is a tree-like structure. The MAIN branch has the SNOMED CT International content, and Extensions basically branch off at their current International version.
Extensions can extend other Extensions in the same CodeSystem, for example a SNOMED CT INT CodeSystem can be extended by a SNOMED CT UK Common Extension and that can be extended further by the Clinical and Drug parts (to allow collaborative authoring for both of them at the same time on the same server).
After many years of perfecting the revision model and implementation, I can safely say that performance is only affected by the number of documents in the index (which can be easily scaled with ES scaling capabilities) and the actual structure you choose to store them (how many branches, depth of the structure etc.) will NOT affect the performance.

> Would it possible to do that through the REST API? (also for the ValueSets and CodeMappings)
No, not at the moment. The REST API does not support ValueSets and CodeMappings, unless you create them as SNOMED CT Reference Sets, which is supported via the dedicated SNOMED CT RefSet and Member APIs.

I hope this answers your questions.

Cheers,
Mark

**Comment by ivelina-yordanova** [comment]
This was very helpful, yes, thank you.

**Comment by cmark** [comment]
Answered. Closing issue.
