### ISSUE TITLE
Query parameters ignored in Swagger UI

### ISSUE THREAD

**Issue by martinmart92** [b2ihealthcare/snow-owl#441]
Hi! 
when trying to use swagger ui `/snomed-ct/v3/{path}/members` and fills `path` and `referenceSet`, only the path parameter is taken into account when executing the query.

The curl and path commands shown in swagger also seem to be missing referenceSet parameter.
When fixing the curl command manually, we do get different results:
incorrect curl from swagger=
```
curl -X GET "https://localhost/snowowl/snomed-ct/v3/MAIN/members" -H "accept: application/json;charset=UTF-8" -H "Accept-Language: en-US;q=0.8,en-GB;q=0.6" -H "authorization: Basic somevalue"
```

expected correct curl fixed manually:
```
curl -X GET "https://localhost/snowowl/snomed-ct/v3/MAIN/members?referenceSet=723561005" -H "accept: application/json;charset=UTF-8" -H "Accept-Language: en-US;q=0.8,en-GB;q=0.6" -H "authorization: Basic somevalue"
```

**Comment by cmark** [comment]
Hi @martinmart92,

Thank you for reporting the issue. 
This indeed a bug in how the Swagger UI v3 handles multi-valued query parameters (or how we generate the api-docs spec). 
We will investigate and get back to you.

Cheers,
Mark

**Comment by cmark** [comment]
Reverted to an earlier version of `swagger-ui-react` dependency, which fixes the problem. Let me know if this works for you.

**Comment by cmark** [comment]
It looks like reverting the dependency did not solve the issue at all. We need to take a deeper look at this issue and why it is happening.
Related swagger-ui ticket: https://github.com/swagger-api/swagger-ui/issues/5119
