### ISSUE TITLE
validate data in a branch

### ISSUE THREAD

**Issue by martinmart92** [b2ihealthcare/snow-owl#442]
when trying to start a validation in `/admin/validations` endpoint, with a sub-branch under MAIN, I get a stacktrace linking to:
https://github.com/b2ihealthcare/snow-owl/blob/07323b8780d78e23e48b2a429bd2ed97e7da0506/core/com.b2international.snowowl.core.rest/src/com/b2international/snowowl/core/rest/validation/ValidationRestService.java#L122

but it works when I ask with branch value being MAIN. I suspect because it's the branch associated with the code system I am using.

Is there a way to validate the data in a sub-branch? That would be an interesting scenario IMHO

**Comment by cmark** [comment]
Hi @martinmart92,

Yes, it looks like this is something that is missing from the implementation. Indeed it would be a good addition and it is already works, but not from the REST API. We will fix this issue for the upcoming `7.2.0` release.

Cheers,
Mark

**Comment by martinmart92** [comment]
understood, thanks for your answer @cmark :)

**Comment by cmark** [comment]
Let's keep this ticket open until we actually resolve the issue. Probably in the upcoming hours the fix will be available and pushed to DockerHub.

**Comment by martinmart92** [comment]
sure, no pb, thank you

**Comment by cmark** [comment]
The issue has been fixed, a new image will be available in an hour or so on DockerHub.
Could you please try and see if resolves the issue at your end @martinmart92 ? 

Thank you,
Mark
