### ISSUE TITLE
concepts vs descriptions search

### ISSUE THREAD

**Issue by mattecasu** [b2ihealthcare/snow-owl#446]
Hello,
a question on search, my scenario is searching labels (descriptions) of concepts, filtering  by ancestors (my ideal response should contain description/label matched and its concept_id):
- I like how `/snomed-ct/v3/{path}/concepts/search` supports filtering by ancestors, but the response doesn't show what terms were actually matched. Is this something that can be added in the response, by using Lucene's highlights for example?
- on the other hand, `/snomed-ct/v3/{path}/descriptions/search` returns the matched labels (although with different results from the concept endpoint, on same inputs) but I don't know whether it's possible to filter by concept's ancestor

Do you have any plans in one of these two directions?
Thanks!

**Comment by apeteri** [comment]
Hi Matteo,

The second approach should be possible with the current version of Snow Owl. The description search endpoint allows you to restrict matches to descriptions on concepts by an ECL expression, which is evaluated over inferred relationships; in addition to that, you can load the properties of the concept associated with matching descriptions through the use of the `expand` option:

```bash
curl -X POST "https://snowowl.b2i.sg/snowowl/snomed-ct/v3/MAIN/descriptions/search" \
-H  "accept: application/json;charset=UTF-8" \
-H  "Accept-Language: en-US;q=0.8,en-GB;q=0.6" \
-H  "Content-Type: application/json" -d "{  \
    \"active\": true,  \
    \"concept\": \"<<404684003|Clinical finding|\", \
    \"expand\": \"concept(expand(fsn()))\", \
    \"limit\": 10, \
    \"term\": \"heart\" \
}"
```

Example response (truncated):

```javascript
{
  "items": [{
      "id": "93561011", // ← Matching description's ID
      "released": true,
      "active": true,
      "effectiveTime": "20170731",
      "moduleId": "900000000000207008",
      "iconId": "900000000000013009",
      "term": "Heart disease", // ← Matching description's term
      "semanticTag": "",
      "languageCode": "en",
      "caseSignificance": "CASE_INSENSITIVE",
      "concept": {
        "id": "56265001", // ← Same as matching description's "concept ID" field
        "released": true,
        "active": true,
        "effectiveTime": "20020131",
        "moduleId": "900000000000207008",
        "iconId": "404684003",
        "definitionStatus": "FULLY_DEFINED",
        "subclassDefinitionStatus": "NON_DISJOINT_SUBCLASSES",
        "fsn": { // ← Fully specified name of the concept that has the matching description
          "id": "794758014",
          "term": "Heart disease (disorder)",
          "concept": {
            "id": "56265001"
          },
          "type": {
            "id": "900000000000003001"
          },
          "conceptId": "56265001",
          "typeId": "900000000000003001",
          "acceptability": {
            "900000000000509007": "PREFERRED",
            "900000000000508004": "PREFERRED"
          }
        },
        [...]
      },
      "type": {
        "id": "900000000000013009" // ← Synonym
      },
      "conceptId": "56265001",
      "typeId": "900000000000013009",
      "acceptability": {
        "900000000000509007": "PREFERRED", // ← Preferred in both dialects
        "900000000000508004": "PREFERRED"  // ←
      }
    }, {
      "id": "350471015",
      "released": true,
      "active": true,
      "effectiveTime": "20170731",
      "moduleId": "900000000000207008",
      "iconId": "900000000000013009",
      "term": "Heart block",
[...]
```

In this case, grouping multiple matching descriptions by concept needs to be done on the client side; this can be facilitated by sorting results on the "conceptId" field.

Let me know if this works for you!

András

**Comment by mattecasu** [comment]
Thanks a lot! I was confused by the difference in the ECL field name ("ecl" for concepts, "concept" for descriptions).
The two endpoints seem to return different results in some cases for same inputs, I guess this is expected since it's a matter of scores in the internal index?

**Comment by apeteri** [comment]
Correct. Another difference is that on the concept search endpoint, individual concepts appear at most once in the result set, with their highest scoring description used as the base for score calculations.

**Comment by mattecasu** [comment]
Thank you very much for the clarifications. I still feel it would be a useful feature to expose the highest scoring description on the concept endpoint, but I understand it might not be a priority. But if you can point me to the relevant point in the codebase I can try and have a look. Thanks for now!

**Comment by apeteri** [comment]
This is the section where the concept search request executes a description search behind the scenes: https://github.com/b2ihealthcare/snow-owl/blob/dd8104bcfadc33ac0e63b4b9eb4ec939687dcbef/snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/request/SnomedConceptSearchRequest.java#L268-L314
