### ISSUE TITLE
Branch merging

### ISSUE THREAD

**Issue by joshlk** [b2ihealthcare/snow-owl#450]
Hi,

When trying to review (so I can then merge) two branches I get the following error:
```
Cannot create review for source 'MAIN/X' and target 'MAIN/Y', because there is no relation between them.
```

I did the following steps:
1. Create branch X from MAIN
2. Create a new concept in X
3. Create branch Y from MAIN
4. Try start a review X source=MAIN/X and target=MAIN/Y

Is this the desired behaviour or a bug?

**Comment by cmark** [comment]
Hi @joshlk,

This error message no longer applies, the 7.x version of Snow Owl can actually create a review even if the branches do not have parent-child relationship. Will be fixed for 7.2.0 release.
Use the Compare API to get back the changes between two branch in the meantime.

Cheers,
Mark

**Comment by joshlk** [comment]
So at the moment with the latest version (`b2ihealthcare/snow-owl-oss:7.x` docker image) you cant merge the two branches?

**Comment by cmark** [comment]
You can merge the two branches, you need to use the `/merges` endpoint for that.
The review endpoints will only get back the concept changes from the compared branch, which can be used for displaying GitHub style compare views.

**Comment by joshlk** [comment]
But to meet you need a review ID. That’s why I’m doing a review. Or has that changed?

**Comment by cmark** [comment]
That is an optional value, or it should be optional, if not then that is a bug.

**Comment by cmark** [comment]
Try to leave it out from the request body.

**Comment by joshlk** [comment]
That worked 👍 . Its not clear in the documentation that review ID is optional. Thanks
