### ISSUE TITLE
Merge status "SCHEDULED"

### ISSUE THREAD

**Issue by joshlk** [b2ihealthcare/snow-owl#451]
Hi,

Ive started a merge process using `POST ​/snomed-ct​/v3​/merges` and then when I check the status using `GET /snomed-ct​/v3​/merges​/{id}` its says the merge status is "SCHEDULED" and the `scheduledDate` is just the time I query `GET /snomed-ct​/v3​/merges​/{id}`. What does "SCHEDULED" mean and how do I get the merge to start?

**Comment by cmark** [comment]
Hi @joshlk,

"SCHEDULED" status means that the request has been accepted but there is no available executor at the moment to start the Job. Merging, Classification and other resource intensive operations use the Job API to run their operations asynchronously and track the progress.
You can query the currently running jobs via the Jobs API `/admin/jobs`.
The available statuses are: `SCHEDULED`, `RUNNING`, `CANCEL_REQUESTED`, `FINISHED`, `FAILED`, `CANCELED`.

If this was the only request in your system and the only job (no classifications, no other merges on the same branch), then I think we need your log files to further investigate the issue.

Regards,
Mark

**Comment by joshlk** [comment]
Thanks for the clarification. Now that I check the `/admin/jobs` endpoint it says the job is RUNNING while `/snomed-ct​/v3​/merges​/{id}` says its SCHEDULED

**Comment by cmark** [comment]
Yes, that is a bug, and I'll push the fix for it in a few minutes.

Cheers,
Mark
