### ISSUE TITLE
Export of FULL/SNAPSHOT on a branch is empty

### ISSUE THREAD

**Issue by psiotwo** [b2ihealthcare/snow-owl#453]
DELTA export of an extension on a branch is working:
`{
	"branchPath" : "MAIN/TEST",
	"extensionOnly": true,
	"moduleIds" : [
		"10000001000242103"
	],
	"type": "DELTA"
}`

but for FULL/SNAPSHOT the export files are generated with empty content.

The three generated exports:
https://filebin.net/i7j6h6d40hsovbwe

**Comment by cmark** [comment]
Hi @psiotwo,

The `extensionOnly` should be set to `true` if the branch you are exporting from is related to an extension CodeSystem of the CodeSystem associated with the `MAIN` branch (there is a parameter to select the CodeSystem you are exporting, `codeSystemShortName`).
If `MAIN/TEST` is just a basic branch and would like to export the content from the perspective of that branch, set the `extensionOnly` flag to `false`. 
Also for Delta exports without date ranges, the `includeUnpublished` flag can be set to `true` to include the unpublished (not yet released) changes.

Cheers,
Mark

**Comment by cmark** [comment]
Hi @psiotwo,

Feel free to reopen this ticket is you have any further questions regarding the RF2 export feature.

Cheers,
Mark
