### ISSUE TITLE
Branches after SNOMED DELTA update

### ISSUE THREAD

**Issue by joshlk** [b2ihealthcare/snow-owl#454]
Hi,

I currently have a branching model of:
* `MAIN` is SNOMED INT (January 2019)
* `MAIN/SNOMEDCT-UK` is the UK edition extension
* `MAIN/SNOMEDCT-UK/BABYLON-UK` is the Babylon extension to the UK edition

After updating SNOMED INT using the latest July 2019 delta using the `/snomed-ct/v3/imports` endpoint `MAIN` has the latest content in it.

To make the latest content available to the other branches presumably the best way would be to rebase them using the `/snomed-ct/v3/merges`. If I rebase `MAIN/SNOMEDCT-UK` will `MAIN/SNOMEDCT-UK/BABYLON-UK` also be rebased? What's the best way of doing it?

**Comment by cmark** [comment]
Hi @joshlk,

Yes, that branching model looks good. You can even depend on specific versions of SNOMED CT if you want and if you have the full history. A version (or tag) is represented as an empty branch basically.
If you rebase a branch, only that branch will be rebased to the new base. Child branches remain there until you rebase them on their parent.
So to get the new July release content to those two child branches of MAIN, you need to execute two rebase operations:
1. `POST /snomed-ct/v3/merges source: MAIN target: MAIN/SNOMEDCT-UK`
2. `POST /snomed-ct/v3/merges source: MAIN/SNOMEDCT-UK target: MAIN/BABYLON-UK`

I hope this helps.
Cheers,
Mark

**Comment by cmark** [comment]
Hi @joshlk,

Feel free to reopen this ticket if you have any further questions.
Closing.

Cheers,
Mark
