### ISSUE TITLE
How to use ValueSet/$validate-code operation

### ISSUE THREAD

**Issue by psiotwo** [b2ihealthcare/snow-owl#494]
Hi,
I created a custom refset with a single SNOMED code in the MAIN/2018-07-31 branch (where I have SNOMED International 2018-07-31 imported).

I am able to see the refset through the GET ValueSet endpoint (see listing below):
`{
  "resourceType": "ValueSet",
  "id": "snomedStore:MAIN/2018-07-31:3741000242102",
  "language": "en-us",
  "url": "http://snomed.info/sct/version/20180731",
  "identifier": {
    "use": "official",
    "system": "http://snomed.info/sct/version/20180731",
    "value": "3741000242102"
  },
  "version": "2018-07-31",
  "name": "Stanford Sleepiness Scale 2",
  "title": "Stanford Sleepiness Scale 2",
  "status": "active",
  "date": "2018-07-31T00:00:00.000+0000",
  "compose": [
    {
      "include": [
        {
          "system": "http://snomed.info/sct",
          "concept": [],
          "filter": [
            {
              "property": "expression",
              "value": "^3741000242102",
              "op": "="
            }
          ],
          "valueSet": []
        }
      ],
      "exclude": []
    }
  ]
}`

But when I try to use ValueSet/$validate-code with code=248220008, system=http://snomed.info/sct, I struggle to invent the correct value for the 'url' and 'version' parameter.  I tried
- url=http://snomed.info/sct/3741000242102/version/20180731  ; version =<empty>
- url=http://snomed.info/sct/3741000242102  ; version=20180731

But either ends with 500 "Query part is missing for value set code validation"

Could you help me understand how to run the $validate-code endpoint?

Thanks

Petr

**Comment by cmark** [comment]
Hi @psiotwo,

The `$validate-code` operation has been rewritten from the ground up to support all scenarios. Feel free to check it out if you'd like in the latest [8.0.0](https://github.com/b2ihealthcare/snow-owl/releases/tag/v8.0.0) release.

Cheers,
Mark
