### ISSUE TITLE
SnowOwl and AWS-Elasticsearch compatibility (versions)

### ISSUE THREAD

**Issue by martinmart92** [b2ihealthcare/snow-owl#496]
hi! Sorry it's a quick question.

Is latest SnowOwl 7.x version compatible with Elasticsearch 7.1?

We're using AWS Elasticsearch and the latest supported version is currently 7.1.

From inspecting SnowOwl's latest commit it seems to currently require 7.5.2 is that correct? We haven't tried it yet but just wanted to double check with you guys first.

Thanks!

**Comment by cmark** [comment]
Hi @martinmart92,

Yes, the latest Snow Owl 7.x Docker image does support Elasticsearch 7.x (Elasticsearch `7.5.2` is the version we are using at the moment).

Cheers,
Mark

**Comment by martinmart92** [comment]
Good news! thanks, we will try compatibility, feel free to close this issue, I'll open it or a new one if something comes up.

**Comment by cmark** [comment]
Cool! Closing this one then.
