### ISSUE TITLE
Sub-en languages not indexed

### ISSUE THREAD

**Issue by mattecasu** [b2ihealthcare/snow-owl#497]
We have found examples of concepts with labels in some sub-English languages (e.g. 999000671000001103 - "National Health Service dictionary of medicines and devices realm language reference set) that are not returned by SnowOwl `concepts/search`. e.g. "serum urea level (observable entity) – snomed id : 1000951000000103".
Maybe SnowOwl does not index these languages by default? Is there a simple config to make it happen?

**Comment by cmark** [comment]
Hi @mattecasu,

Snow Owl indexes all available language reference set members and descriptions and makes them available for search by default.
 
The `Accept-Language` header controls both the underlying `term` search and the `pt()`/`fsn()` expansion when making a search request. The header format supports the standard language tags and weights (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) and the `en-x-<languageRefSetId>` format.

If you would like to use the standard `en`, `en-gb`, `en-us`, etc. language tags then you can configure which language reference sets are searched when such language tag value is specified in the `Accept-Language` header. 

Modify the `snomed.languages` configuration setting in the `snowowl.yml` file and restart the server.
The default configuration value is the following:
https://github.com/b2ihealthcare/snow-owl/blob/7.x/releng/com.b2international.snowowl.server.update/assembly/common/configuration/snowowl.yml#L28-L38

If you would like to be more dynamic then you can use the `en-x-<languageRefSetId>` format in the concept search request. 
In your case, use the `en-x-999000671000001103` value in the `Accept-Language` header and the mentioned concept should be returned with its proper `pt()`/`fsn()`.

Example curl:

```
curl -X GET "http://localhost:8080/snowowl/snomed-ct/v3/MAIN%2F2018-07-31%2FSNOMEDCT-UK-CL/concepts?active=true&expand=pt()&id=1000951000000103&limit=50&term=Serum%20urea%20level" -H "accept: application/json;charset=UTF-8" -H "Accept-Language: en,en-x-999000671000001103"
```

And response:

```
{
  "items": [
    {
      "id": "1000951000000103",
      "released": true,
      "active": true,
      "effectiveTime": "20160401",
      "moduleId": "999000011000000103",
      "iconId": "363787002",
      "definitionStatus": {
        "id": "900000000000074008"
      },
      "subclassDefinitionStatus": "NON_DISJOINT_SUBCLASSES",
      "pt": {
        "id": "2560931000000113",
        "term": "Serum urea level",
        "concept": {
          "id": "1000951000000103"
        },
        "type": {
          "id": "900000000000013009"
        },
        "typeId": "900000000000013009",
        "conceptId": "1000951000000103",
        "acceptability": {
          "900000000000508004": "PREFERRED",
          "999001261000000100": "PREFERRED"
        }
      },
      "ancestorIds": [
        "373063009",
        "138875005",
        "993641000000107",
        "-1",
        "363787002"
      ],
      "parentIds": [
        "1028281000000106"
      ],
      "statedAncestorIds": [
        "373063009",
        "138875005",
        "993641000000107",
        "-1",
        "363787002"
      ],
      "statedParentIds": [
        "1028281000000106"
      ],
      "definitionStatusId": "900000000000074008"
    }
  ],
  "searchAfter": "AoIIQDsuoj8FMDZlNTU1MjUtNDI1YS00YjA1LWFjMDUtNDkxNDg3MjhkODYw",
  "limit": 50,
  "total": 1
}
```

If you remove the `id` filter you will get back other terms as well, but the concept in question should be part of the response and the `pt()` should be expanded to the proper description term.

I hope this answers your questions.

Cheers,
Mark

**Comment by mattecasu** [comment]
Thanks a lot Mark!
I noticed that on some endpoints there are also other ways of asking/filtering for the language (e.g. `descriptions/search` has "languageCode"), the Accept-language header being one of them. Is it advisable to always prefer the header?

**Comment by cmark** [comment]
Hi @mattecasu,

The `languageCode` is a property of a SNOMED CT Description. That filter will match the `languageCode`s stored in the description itself. See more details here: 
https://confluence.ihtsdotools.org/display/DOCRELFMT/4.2.2+Description+File+Specification

The `Accept-Language` header controls the display language used for filtering by term and when expanding `pt()` and `fsn()` for a concept (just like with the web, the Accept-Language header specifies the language of the client and can be used to determine which language to search/render etc.).

I hope this clarifies.

Cheers,
Mark

**Comment by mattecasu** [comment]
Thank you again for the clarification Mark. What I have in mind is more what happens with descriptions that are not pt or fsn. For example, if we want `en-gb`, non-preferred descriptions, at the moment we get all descriptions and filter them by looking at the acceptability map.

**Comment by cmark** [comment]
Regarding searching all descriptions participate in the search process, be it `preferred`/`acceptable`, so you are able to find a concept via any of its descriptions using the `term` filter.
Regarding expansion of `pt()` and/or `fsn()`, only preferred synonyms can be expanded as `pt()` and only preferred fully specified names can be expanded as `fsn()`, other descriptions cannot be expanded using these options.
If your use case requires a non-preferred description to be displayed, then I suggest expanding the concept's descriptions via `descriptions()` or using the description endpoints for more fine-grained searches.

Cheers,
Mark

**Comment by cmark** [comment]
Closing as resolved. Feel free to reopen if you have any further questions.
