### ISSUE TITLE
Would it make sense to allow bulk requests for labels ?

### ISSUE THREAD

**Issue by ivelina-yordanova** [b2ihealthcare/snow-owl#498]
Hi,

We have a use case for querying multiple labels at once but this at the moment can only be done one by one, which results in a seemingly too high of a load for the server and it dies for a while, without returning anything.

I was  looking for a way to request them at once but could not find anything we could use. Have you considered adding this option to the snomedct api or are there concerns preventing you from doing this at this point (maybe besides other priorities :D ) 

Thanks,
Ivelina

**Comment by ivelina-yordanova** [comment]
(continued ..) or maybe allow label expansion along with the relationship request for example ?

**Comment by apeteri** [comment]
Hi @ivelina-yordanova,

The latter is indeed possible, by expanding any of the relationship's concept properties, and supplying a nested expand option for the property (the example query retrieves active, inferred relationships of `<<404684003 |Clinical finding|` with type `363698007 |Finding site|`):

```shell
$ curl "https://hostname/snowowl/snomed-ct/v3/MAIN/relationships?\
active=true&\
characteristicType=900000000000011006&\
expand=destination(expand(pt()))&\
limit=10\
&source=%3C%3C404684003\
&type=363698007" \
-H "accept: application/json;charset=UTF-8" \
-H "Accept-Language: en-US;q=0.8,en-GB;q=0.6" \
-H "authorization: Basic <token>"
```

```javascript
{
  "items": [{
      "id": "3780963029",
      "released": true,
      "active": true,
      "effectiveTime": "20100731",
      "moduleId": "900000000000207008",
      "iconId": "363698007",
      "destinationNegated": false,
      "group": 1,
      "unionGroup": 0,
      "characteristicType": "INFERRED_RELATIONSHIP",
      "modifier": "EXISTENTIAL",
      "source": {
        "id": "443089001"
      },
      "destination": { // ← properties of the destination concept
        "id": "113257007",
        "released": true,
        "active": true,
        "effectiveTime": "20020131",
        "moduleId": "900000000000207008",
        "iconId": "123037004",
        "definitionStatus": "PRIMITIVE",
        "subclassDefinitionStatus": "NON_DISJOINT_SUBCLASSES",
        "pt": { // ← the destination concept's PT
          "id": "2642196011",
          "term": "Structure of cardiovascular system",
          "concept": {
            "id": "113257007"
          },
          "type": {
            "id": "900000000000013009"
          },
          "typeId": "900000000000013009",
          "conceptId": "113257007",
          "acceptability": {
            "900000000000509007": "PREFERRED",
            "900000000000508004": "PREFERRED"
          }
        },
        "ancestorIds": ["138875005", "91723000", "442083009", "-1", "123037004"],
        "parentIds": ["91689009"],
        "statedAncestorIds": ["138875005", "91723000", "442083009", "-1", "123037004"],
        "statedParentIds": ["91689009"],
        "definitionStatusId": "900000000000074008"
      },
      "type": {
        "id": "363698007"
      },
      "typeId": "363698007",
      "sourceId": "443089001",
      "destinationId": "113257007",
      "characteristicTypeId": "900000000000011006",
      "modifierId": "900000000000451002"
    },
    ...
  ],
  "searchAfter":"AoE_BTAwMDY5ODc0LTFjMDYtNDQwMC1hZmY2LWNmNjE4OTQxNDdlZQ==",
  "limit":10,
  "total":88056
}
```

You do get all concept properties for `destination`, in addition to description properties of `pt`, which may or may not be warranted in your use case. We are hoping to address this by exposing a field selection mechanism in the future.

A slightly faster sub-alternative is to use `destination(expand(preferredDescriptions()))` as the expand option, which will return more concise description fragments for the (destination) concept, that have an active preferred language reference set member, regardless of the value given in the `Accept-Language` header:

```javascript
{
  "items": [{
      "id": "3780963029",
      "released": true,
      "active": true,
      "effectiveTime": "20100731",
      "moduleId": "900000000000207008",
      "iconId": "363698007",
      "destinationNegated": false,
      "group": 1,
      "unionGroup": 0,
      "characteristicType": "INFERRED_RELATIONSHIP",
      "modifier": "EXISTENTIAL",
      "source": {
        "id": "443089001"
      },
      "destination": {
        "id": "113257007",
        "released": true,
        "active": true,
        "effectiveTime": "20020131",
        "moduleId": "900000000000207008",
        "iconId": "123037004",
        "definitionStatus": "PRIMITIVE",
        "subclassDefinitionStatus": "NON_DISJOINT_SUBCLASSES",
        "preferredDescriptions": { // ← descriptions with "Preferred" acceptability of the destination concept
          "items": [{
              "id": "2638096015",
              "term": "Structure of cardiovascular system (body structure)",
              "concept": {
                "id": "113257007"
              },
              "type": {
                "id": "900000000000003001"
              },
              "typeId": "900000000000003001",
              "conceptId": "113257007",
              "acceptability": {
                "900000000000509007": "PREFERRED",
                "900000000000508004": "PREFERRED"
              }
            }, {
              "id": "2642196011",
              "term": "Structure of cardiovascular system",
              "concept": {
                "id": "113257007"
              },
              "type": {
                "id": "900000000000013009"
              },
              "typeId": "900000000000013009",
              "conceptId": "113257007",
              "acceptability": {
                "900000000000509007": "PREFERRED",
                "900000000000508004": "PREFERRED"
              }
            }
          ],
          "limit": 2,
          "total": 2
        },
        "ancestorIds": ...
```
Regards,
András

**Comment by ivelina-yordanova** [comment]
Hi András,

That's awesome, thank you!

I tried to find more info as to what can be extended for the relationships endpoint but didn't find much. Have I missed it? Do you have documentation about it? Is it different for each endpoint or is it common across all?

Thanks and regards,
Ivelina

**Comment by apeteri** [comment]
Expansion of a property happens in overridden methods of `BaseResourceConverter#toResource(T)` and `BaseResourceConverter#expand(List<R>)`, eg. for `SnomedRelationship` objects in `SnomedRelationshipConverter`: https://github.com/b2ihealthcare/snow-owl/blob/4535427599a70961b55127f41b53a36d860d910e/snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/converter/SnomedRelationshipConverter.java#L68-L82

In terms of what property can be expanded at all, these are collected in a nested class named `Expand` on each component: https://github.com/b2ihealthcare/snow-owl/blob/4535427599a70961b55127f41b53a36d860d910e/snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/core/domain/SnomedRelationship.java#L70-L81

**Comment by ivelina-yordanova** [comment]
Right, OK, thank you for replying so quickly!

**Comment by apeteri** [comment]
No problem! Do let us know if you have other questions or problems.
