### ISSUE TITLE
Match filters / wildcards in GET queries?

### ISSUE THREAD

**Issue by incansvl** [b2ihealthcare/snow-owl#632]
SnowOwl: 7.8.2
Endpoint: /snomed-ct/v3/branches (GET)

First experiments in using the RESTful services in Snow Owl. Documentation is lacking, so it's hard to work out what is possible.

Situation
---------
I'm working on a decendant module of the SNOMED International MAIN branch. I thought it was configured as grandchild, but the paths are exposed via REST as **MAIN/<main_ver>/MODULENAME/<module_ver>**

I can specify a (fixed) name or parent name to search for as a parameter, but that doesn't help me (say) find the latest branch/version number in my module, because there are two variable version numbers in the path.

It appears that the only way to do this at the moment is pull down every branch path that exists on the server, then filter the list for my module name, and the latest timestamp.

Ideally the interface would support a "path" parameter plus wildcards and/or regular expressions in the path type parameters. so I could specify **`?path=".*/SNOMEDCT-UK-PA/.*"`** in the query

Is this possible now, or a potential enhancement?

**Comment by cmark** [comment]
Hi @incansvl,

Thank you for raising your issue.

> Is this possible now, or a potential enhancement?

This is not possible at the moment, `path` arguments do not support regular expressions nor wildcards.


The branch path endpoints are designed to work with the actual branches in the low-level system, create sandboxed environments, merge them, etc.
When you are looking for the latest version of a CodeSystem, say for your SNOMED CT Extension, use the `GET /admin/codesystems/{shortName}/versions` to find the latest version, the returned list is ordered by the `versionId` field (other sort parameters will be added soon to the endpoint) which in case of SNOMED should always be a `yyyy-MM-dd` value, so the last returned entry is your latest SNOMED CT version.
Also, if you would like to query the last version of your SNOMED CT Extension another option is to use the special path URI syntax:
* `<CodeSystemShortName>/LATEST` - points to the latest version of the specified CodeSystem (eg. `SNOMEDCT-UK-PA/LATEST`)
* `<CodeSystemShortName>/HEAD` - points to the latest development version of the specified CodeSystem (eg. `SNOMEDCT-UK-PA/HEAD`)
* `<CodeSystemShortName>/<versionId>` - points to a specific version of the specified CodeSystem (eg. `SNOMEDCT-UK-PA/2020-08-11`)
* `<CodeSystemShortName>/<path>` - any other relative path to query content (eg. a child branch where you edit the content for example, `SNOMEDCT-UK-PA/fix-content-branch`)

I hope this answers your questions, let us know if you have any further ones.

Regards,
Mark

**Comment by incansvl** [comment]
Thanks for the information. Whether this helps in my situation depends on what you mean by "version".  At least some of the time I am looking for pre-release (unversioned) content, which appears to be represented in the branch hierarchy by paths ending in numbers (task IDs?). If unversioned content does not appear under the /admin/codesystems endpoint then that would not be an option.

However the use of a named child branch (your fix-content-branch example) of MAIN wasn't something I had realised Snow Owl supported. I will look into that. Thanks.

**Comment by cmark** [comment]
Hi @incansvl,

A version is similar to a Git tag, a point in time which you would like to reference at a later point in time (a release for example).
See this link for more info: https://docs.b2i.sg/snow-owl/index/basic-concepts#version

The `/admin/codesystems` endpoints are responsible for returning the Code Systems and the corresponding Code System Versions (for example the SNOMED CT 2020 July 31 release version), to access the SNOMEDCT content, you need to use the endpoints available under `/snomed-ct/v3/` path.

To retrieve the current development version (all versioned + the unversioned, unreleased content) then I suggest using the `<CodeSystemShortName>/HEAD` URI or the actual absolute path `MAIN/2020-07-31/SNOMEDCT-MYEXT`.
For example, to retrieve concepts that have descriptions with the word `diabetes` you can use the following request:

```
GET /snomed-ct/v3/SNOMEDCT-MYEXT/HEAD/concepts?term=diabetes
```

But if you would like to retrieve content from the last versioned release of your extension or any other SNOMED CT CodeSystem, you can use the following:

```
GET /snomed-ct/v3/SNOMEDCT-MYEXT/2020-08-11/concepts?term=diabetes
```

You can create unlimited amount of branches and unlimited depth, but we usually recommend stick to the golden rule of `make it simple`. One branch for the main development version along with your release versions/tags and small task branches to alter the content.

Let me know if you have any further questions.

Cheers,
Mark

**Comment by incansvl** [comment]
Thanks Mark, I'm somewhat familiar with Git (at a very inexpert level). When I looked at the way we were using SO in the UK it seemed rather less general that Git, but it appears those may be 'habits' rather than limitations of the tool. I clearly need to read the docs rather than looking at current practice ;-)
