### ISSUE TITLE
Exception when processing ECL request

### ISSUE THREAD

**Issue by ivelina-yordanova** [b2ihealthcare/snow-owl#658]
**Describe the bug**
When searching a concept by ECL expression that includes a wildcard `*`, the server throws exceptions and response with 500. After looking a bit into this it seems like the root cause of the issue is the ElasticSearch cluster size - there are network limits, different for the different cluster sizes https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html. Ours in dev has limit 10MB, but even in prod where the limit is 100MB some of the queries fail. 

Even though the root cause is the max size of HTTP request payload allowed as per the ES limitations it seems unreasonable to have to send a request of over 100MB, so maybe this bit can be either optimised or maybe use scrolling to mitigate that on a request level in SnowOwl. 

**To Reproduce**

Here are couple of random examples of ECL to use:
1.  " << * :  *  =  *"    - this doesn't worn in both cluster sizes
2. "<< * :  246090004  =  *"   - this works in the larger size

**Expected behavior**
I would have expected limit in the request to snowowl to play a role in the request to ES as well or maybe have different param or config to control the ES requests. However, the expected behaviour is just a proper returned response. Currently the response is 500 with message `Something went wrong during the processing of your request.`

**Version**
 - Snow Owl Version:  v7.9.1 
 - Elasticsearch Version (external): 7.7.0

**Additional context**
Parts of the stacktrace include

>      ERROR index.snomedstore - Couldn't execute query 

followed by

>.    Suppressed: org.elasticsearch.common.ParsingException: Failed to parse object: expecting field with name [error] but found [Message]

where the response seems to be :

> {"Message":"Request size exceeded 10485760 bytes"}

**Comment by cmark** [comment]
Hi @ivelina-yordanova,

Thank you for reporting the issue.
Yes, this is something that has been reported from other sources, where AWS is being used.
We will take the time to limit the size of the requests Snow Owl sends to an ES cluster, but at the current state this is not supported.
As a possible workaround, in some cases limiting the ECL query or splitting up the ECL query manually on the input side could work, but I see this is not an ideal solution to the problem.

Once we have the fixes, I'll get back to you.

Regards,
Mark

**Comment by ivelina-yordanova** [comment]
Hi @cmark,

Thank you for replying so quickly. I am suspecting the size limit is also the main issue we cannot save the results of the classification job (see [this issue](https://github.com/b2ihealthcare/snow-owl/issues/578)), which is quite important for us at the moment, so I was wondering if you have an approximate timeline or estimation when/ in what release do you expect to have a fix for this, otherwise we'll have to look for workarounds for that as well.

Thanks,
Ivelilna

**Comment by cmark** [comment]
Hi @ivelina-yordanova,

Not 100% sure that the two issues are actually connected or one is the reason of the other, but if yes, then handling large filters and request body sizes in our Elasticsearch client layer will definitely solve the issue. I'd like to fix these issues as soon as possible and it will happen eventually, but I cannot guarantee any specific release version or any release date. 

I hope you understand.
Contributions are always welcome, feel free to play with the low-level parts of our ES client layer and submit your changes.

Regards,
Mark

**Comment by ivelina-yordanova** [comment]
Hi @cmark,

Completely understand.

Just wanted to share another observation in case that's useful - we did an experiment with a larger cluster, where the payload limit is 10x more and this worked for the classification issue and given the logs from the issue I assume they are for sure related.

Regards,
Ivelina

**Comment by cmark** [comment]
Thank you!
Mark

**Comment by cmark** [comment]
Hi @ivelina-yordanova,

Do you have any updates on this? Did you encounter the occasional failures of ECL evaluation either in your dev or prod environments? 
We have made several improvements to proper Elasticsearch request sizing in recent releases, but some of the areas might need extra care. 

Any update on this is greatly appreciated.

Thank you,
Mark

**Comment by cmark** [comment]
Hi @ivelina-yordanova,

Multiple improvements have been introduced in the ECL processing and evaluation of the latest [8.0.0](https://github.com/b2ihealthcare/snow-owl/releases/tag/v8.0.0) release that hopefully help with the failures you have experienced in this ticket. Feel free to check them out.

As always, if you have any further questions or experience any other issues, raise them here.

Cheers,
Mark
