### ISSUE TITLE
Issue with Delta import of Snomed Uk

### ISSUE THREAD

**Issue by cristinacivili-work** [b2ihealthcare/snow-owl#699]
Hello,

We are having some issues with the import of a Delta Snomed Uk update.

This is our structure:
- MAIN/2018-07-31/SNOMEDCT-UK/2019-06-01 is our most recent branch
- SNOMEDCT2_28.0.0_20191001000001 is the oldest Snomed Uk update we need to import.

Our steps are the following:
- create a branch 2019-10-01 with parent MAIN/2018-07-31/SNOMEDCT-UK/
- import archive SNOMEDCT2_28.0.0_20191001000001 into MAIN/2018-07-31/SNOMEDCT-UK/ 2019-10-01
- check the import commit on the branch and, if the import succeeds, merge MAIN/2018-07-31/SNOMEDCT-UK/2019-06-01 into MAIN/2018-07-31/SNOMEDCT-UK/ 2019-10-01

The problem is that, with archive SNOMEDCT2_28.0.0_20191001000001, the import doesn't produce any commit on the branch. There are no errors in the log, except for a few unrecognized snomed ids, and the import apparently succeeds, but the branch is just empty.

We have tried with other archives and it works perfectly fine, but we need this one first. 

Any suggestion on what we could be doing wrong or anything we can check? 

Thanks,
Cristina

**Comment by cmark** [comment]
Hi @cristinacivili-work,

Could you please send us some relevant logs from Snow Owl to aid the investigation?
What kind of content you have imported and on which branch in your Snow Owl instance?
Is the `SNOMEDCT2_28.0.0_20191001000001` an official UK Clinical RF2 archive?

Usually, the import produces no commit because of the following two reasons:
* There is nothing to actually commit, because you already have all the data imported on the branch.
* There are structural (inconsistent file structure, invalid IDs, etc.) validation errors that prevent importing the selected RF2 data 

Thank you,
Mark

**Comment by cristinacivili-work** [comment]
Hi Mark,
thank you for your reply.

**SNOMEDCT2_28.0.0_20191001000001** an official UK Clinical RF2 (Delta only) archive.
Our installation is in sync with releases up to June 2019, and this is the first Delta we need to import to update our data.

The current content is in branch **MAIN/2018-07-31/SNOMEDCT-UK/2019-06-01** while the import attempt was in branch **MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01**

By manually looking at the archive files, it looks like there are at least a few new concepts to import in that release, so I think it is unlikely that there is nothing to commit. But there were some error messages, so your second option may explain the issue. 

Please find below the logs of the import attempt. 

Oct 21, 2020 @ 15:30:32.286	[2020-10-21 14:30:32.286] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  index.jobs - Updated 1 job documents with bulk update with script 'withDone' 

	Oct 21, 2020 @ 15:30:32.265	[2020-10-21 14:30:32.265] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  lock - Lock released for branch 'MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01' of repository 'snomedStore' (importing release file content). 

	Oct 21, 2020 @ 15:30:32.253	[2020-10-21 14:30:32.252] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] ERROR import - Component refers to a non-existing description with id '1916701000000112' in effective time '2019-10-01' 

	Oct 21, 2020 @ 15:30:32.253	[2020-10-21 14:30:32.252] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] ERROR import - Component refers to a non-existing description with id '1916711000000114' in effective time '2019-10-01' 

	Oct 21, 2020 @ 15:30:32.253	[2020-10-21 14:30:32.252] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] ERROR import - Component refers to a non-existing description with id '1916691000000112' in effective time '2019-10-01' 

	Oct 21, 2020 @ 15:30:32.252	[2020-10-21 14:30:32.252] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] ERROR import - Component refers to a non-existing description with id '1916681000000110' in effective time '2019-10-01' 

	Oct 21, 2020 @ 15:30:32.252	[2020-10-21 14:30:32.252] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] ERROR import - Component refers to a non-existing description with id '1916721000000115' in effective time '2019-10-01' 

	Oct 21, 2020 @ 15:30:06.663	[2020-10-21 14:30:06.663] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - Validating component consistency in effective time '2019-09-19' 

	Oct 21, 2020 @ 15:30:06.663	[2020-10-21 14:30:06.662] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - Preparing RF2 import took: 9.111 s 

	Oct 21, 2020 @ 15:30:06.663	[2020-10-21 14:30:06.663] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - Validating component consistency in effective time '2019-10-01' 

	Oct 21, 2020 @ 15:30:06.578	[2020-10-21 14:30:06.578] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Terminology/sct2_sRefset_OwlExpressionDelta_GB1000000_20191001.txt - 67.17 μs 

	Oct 21, 2020 @ 15:30:06.578	[2020-10-21 14:30:06.578] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Terminology/sct2_TextDefinition_Delta-en_GB1000000_20191001.txt - 67.81 μs 

	Oct 21, 2020 @ 15:30:06.578	[2020-10-21 14:30:06.578] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Terminology/sct2_StatedRelationship_Delta_GB1000000_20191001.txt - 73.15 μs 

	Oct 21, 2020 @ 15:30:06.578	[2020-10-21 14:30:06.578] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Terminology/sct2_Relationship_Delta_GB1000000_20191001.txt - 6.573 ms 

	Oct 21, 2020 @ 15:30:06.571	[2020-10-21 14:30:06.571] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Terminology/sct2_Description_Delta-en_GB1000000_20191001.txt - 5.163 ms 

	Oct 21, 2020 @ 15:30:06.571	[2020-10-21 14:30:06.571] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Terminology/sct2_Identifier_Delta_GB1000000_20191001.txt - 109.3 μs 

	Oct 21, 2020 @ 15:30:06.571	[2020-10-21 14:30:06.571] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] WARN  import - Unrecognized RF2 file: SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Terminology/sct2_Identifier_Delta_GB1000000_20191001.txt 

	Oct 21, 2020 @ 15:30:06.566	[2020-10-21 14:30:06.565] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Terminology/sct2_Concept_Delta_GB1000000_20191001.txt - 1.438 ms 

	Oct 21, 2020 @ 15:30:06.564	[2020-10-21 14:30:06.564] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Refset/Metadata/der2_sssssssRefset_MRCMDomainDelta_GB1000000_20191001.txt - 72.75 μs 

	Oct 21, 2020 @ 15:30:06.564	[2020-10-21 14:30:06.564] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Refset/Metadata/der2_ssRefset_ModuleDependencyDelta_GB1000000_20191001.txt - 1.038 ms 

	Oct 21, 2020 @ 15:30:06.563	[2020-10-21 14:30:06.563] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Refset/Metadata/der2_ssccRefset_MRCMAttributeRangeDelta_GB1000000_20191001.txt - 52.88 μs 

	Oct 21, 2020 @ 15:30:06.563	[2020-10-21 14:30:06.562] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Refset/Metadata/der2_cRefset_MRCMModuleScopeDelta_GB1000000_20191001.txt - 53.11 μs 

	Oct 21, 2020 @ 15:30:06.562	[2020-10-21 14:30:06.562] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Refset/Metadata/der2_cissccRefset_MRCMAttributeDomainDelta_GB1000000_20191001.txt - 54.41 μs 

	Oct 21, 2020 @ 15:30:06.562	[2020-10-21 14:30:06.562] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] WARN  import - Unrecognized RF2 file: SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Refset/Metadata/der2_cciRefset_RefsetDescriptorDelta_GB1000000_20191001.txt 

	Oct 21, 2020 @ 15:30:06.562	[2020-10-21 14:30:06.562] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Refset/Metadata/der2_ciRefset_DescriptionTypeDelta_GB1000000_20191001.txt - 56.91 μs 

	Oct 21, 2020 @ 15:30:06.562	[2020-10-21 14:30:06.562] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Refset/Metadata/der2_cciRefset_RefsetDescriptorDelta_GB1000000_20191001.txt - 146.0 μs 

	Oct 21, 2020 @ 15:30:06.562	[2020-10-21 14:30:06.562] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Refset/Map/der2_iissscRefset_ComplexMapDelta_GB1000000_20191001.txt - 169.6 μs 

	Oct 21, 2020 @ 15:30:06.562	[2020-10-21 14:30:06.562] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Refset/Map/der2_sRefset_SimpleMapDelta_GB1000000_20191001.txt - 55.88 μs 

	Oct 21, 2020 @ 15:30:06.561	[2020-10-21 14:30:06.561] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Refset/Map/der2_iisssciRefset_ExtendedMapDelta_GB1000000_20191001.txt - 881.8 ms 

	Oct 21, 2020 @ 15:30:05.679	[2020-10-21 14:30:05.679] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Refset/Language/der2_cRefset_LanguageDelta-en_GB1000000_20191001.txt - 59.14 ms 

	Oct 21, 2020 @ 15:30:05.679	[2020-10-21 14:30:05.679] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Refset/Map/der2_iisssccRefset_ExtendedMapDelta_GB1000000_20191001.txt - 103.1 μs 

	Oct 21, 2020 @ 15:30:05.620	[2020-10-21 14:30:05.620] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Refset/Content/der2_Refset_SimpleDelta_GB1000000_20191001.txt - 8.060 s 

	Oct 21, 2020 @ 15:29:57.560	[2020-10-21 14:29:57.560] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Refset/Content/der2_cRefset_AttributeValueDelta_GB1000000_20191001.txt - 1.858 ms 

	Oct 21, 2020 @ 15:29:57.558	[2020-10-21 14:29:57.558] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_UKClinicalRF2_PRODUCTION_20191001T000001Z/Delta/Refset/Content/der2_cRefset_AssociationDelta_GB1000000_20191001.txt - 1.004 ms 

	Oct 21, 2020 @ 15:29:57.557	[2020-10-21 14:29:57.556] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Terminology/sct2_StatedRelationship_Delta_INT_20181031.txt - 61.57 μs 

	Oct 21, 2020 @ 15:29:57.557	[2020-10-21 14:29:57.557] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Terminology/sct2_TextDefinition_Delta-en_INT_20181031.txt - 65.65 μs 

	Oct 21, 2020 @ 15:29:57.556	[2020-10-21 14:29:57.556] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Terminology/sct2_sRefset_OWLOntologyDelta_INT_20181031.txt - 50.80 μs 

	Oct 21, 2020 @ 15:29:57.556	[2020-10-21 14:29:57.556] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] WARN  import - Unrecognized RF2 file: SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Terminology/sct2_Identifier_Delta_INT_20181031.txt 

	Oct 21, 2020 @ 15:29:57.556	[2020-10-21 14:29:57.556] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Terminology/sct2_Relationship_Delta_INT_20181031.txt - 62.22 μs 

	Oct 21, 2020 @ 15:29:57.556	[2020-10-21 14:29:57.556] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Terminology/sct2_sRefset_OWLAxiomDelta_INT_20181031.txt - 54.77 μs 

	Oct 21, 2020 @ 15:29:57.556	[2020-10-21 14:29:57.556] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Terminology/sct2_Identifier_Delta_INT_20181031.txt - 115.1 μs 

	Oct 21, 2020 @ 15:29:57.555	[2020-10-21 14:29:57.555] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Refset/Metadata/der2_ssccRefset_MRCMAttributeRangeDelta_INT_20181031.txt - 57.12 μs 

	Oct 21, 2020 @ 15:29:57.555	[2020-10-21 14:29:57.555] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Refset/Metadata/der2_ssRefset_ModuleDependencyDelta_INT_20181031.txt - 57.40 μs 

	Oct 21, 2020 @ 15:29:57.555	[2020-10-21 14:29:57.555] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Terminology/sct2_Description_Delta-en_INT_20181031.txt - 53.13 μs 

	Oct 21, 2020 @ 15:29:57.555	[2020-10-21 14:29:57.555] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Terminology/sct2_Concept_Delta_INT_20181031.txt - 69.70 μs 

	Oct 21, 2020 @ 15:29:57.555	[2020-10-21 14:29:57.555] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Refset/Metadata/der2_sssssssRefset_MRCMDomainDelta_INT_20181031.txt - 64.42 μs 

	Oct 21, 2020 @ 15:29:57.554	[2020-10-21 14:29:57.554] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Refset/Map/der2_sRefset_SimpleMapDelta_INT_20181031.txt - 56.15 μs 

	Oct 21, 2020 @ 15:29:57.554	[2020-10-21 14:29:57.554] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Refset/Metadata/der2_cciRefset_RefsetDescriptorDelta_INT_20181031.txt - 91.65 μs 

	Oct 21, 2020 @ 15:29:57.554	[2020-10-21 14:29:57.554] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] WARN  import - Unrecognized RF2 file: SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Refset/Metadata/der2_cciRefset_RefsetDescriptorDelta_INT_20181031.txt 

	Oct 21, 2020 @ 15:29:57.554	[2020-10-21 14:29:57.554] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Refset/Metadata/der2_cissccRefset_MRCMAttributeDomainDelta_INT_20181031.txt - 57.23 μs 

	Oct 21, 2020 @ 15:29:57.554	[2020-10-21 14:29:57.554] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Refset/Metadata/der2_ciRefset_DescriptionTypeDelta_INT_20181031.txt - 59.68 μs 

	Oct 21, 2020 @ 15:29:57.554	[2020-10-21 14:29:57.554] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Refset/Metadata/der2_cRefset_MRCMModuleScopeDelta_INT_20181031.txt - 74.92 μs 

	Oct 21, 2020 @ 15:29:57.553	[2020-10-21 14:29:57.553] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Refset/Content/der2_Refset_SimpleDelta_INT_20181031.txt - 68.95 μs 

	Oct 21, 2020 @ 15:29:57.553	[2020-10-21 14:29:57.553] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Refset/Map/der2_iisssccRefset_ExtendedMapDelta_INT_20181031.txt - 73.34 μs 

	Oct 21, 2020 @ 15:29:57.553	[2020-10-21 14:29:57.553] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Refset/Content/der2_cRefset_AttributeValueDelta_INT_20181031.txt - 85.35 μs 

	Oct 21, 2020 @ 15:29:57.553	[2020-10-21 14:29:57.553] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Refset/Language/der2_cRefset_LanguageDelta-en_INT_20181031.txt - 59.70 μs 

	Oct 21, 2020 @ 15:29:57.553	[2020-10-21 14:29:57.552] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  import - SnomedCT_InternationalRF2_PRODUCTION_20180731T120000Z/Delta/Refset/Content/der2_cRefset_AssociationDelta_INT_20181031.txt - 170.0 μs 

	Oct 21, 2020 @ 15:29:57.534	[2020-10-21 14:29:57.533] [Worker-1: snomed-import-MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01] INFO  lock - Lock acquired for branch 'MAIN/2018-07-31/SNOMEDCT-UK/2019-10-01' of repository 'snomedStore' (importing release file content). 

Thanks,
Cristina

**Comment by cmark** [comment]
Hi @cristinacivili-work,

That is the source of the issue then.
The branch `2019-10-01` does not have any UK content, neither on that branch directly nor on the parent branches.
I would expect the UK content to be present on the SNOMEDCT-UK branch and the `2019-06-01` branch an "empty" version branch. By empty I mean like a Git tag, a reference to a point where the UK content represents the 2019-06-01 version.

If the data lives on the SNOMEDCT-UK branch, then feel free to import it onto that branch with the `createVersion` boolean flag set to `true`. That will implicitly create all necessary version branches (based on the effective time values in the source file) during import, so in the end the `2019-10-01` should be available, and should have all the data from the input RF2 delta file loaded properly.

Hint: The Extension management documentation has very descriptive images and scenarios to help you understand Snow Owl's branching/versioning features and how an extension can be represented in Snow Owl.

I hope this clarifies your question, let me know if you have any further.

Cheers,
Mark

**Comment by cristinacivili-work** [comment]
Hi @cmark,
thank you very much for the explanation, I was finally able to import the archive by importing directly into **MAIN/2018-07-31/SNOMEDCT-UK**.
In order to do so, however, I also had to amend manually the archive by removing the IDs that were causing validation errors. This operation is very time consuming and error prone. Is there a way to configure the import so that the validation errors won't block the process and the rows containing "bad IDs" will just be ignored? 

Thanks,
Cristina

**Comment by cmark** [comment]
Hi @cristinacivili-work,

Yes, I understand hacking the RF2 file is not the best solution when it comes to importing it without errors into Snow Owl.
So far, we have used internal tools and other scripts to modify the content of an RF2 archive to make it importable into Snow Owl, but that is unfortunately cannot be open sourced yet.
At the moment, there is no way to filter out components that reference missing content (or ignore the validation issue), because that might break something in the long run (especially when it comes to core SNOMED CT components). 
I see two possible enhancements here:
1. Allow the import to filter out/ignore non-metadata reference set members (like mappings and simple type members). This is a common scenario we deal with with our internal tools and it would be a great addition to the open-source RF2 import feature set.
2. Expose an RF2 archive validator endpoint that can validate the incoming package against the currently stored content.

Let us know if you have any further issues with RF2 imports.

Thank you for your feedback and ideas,
Mark

**Comment by cristinacivili-work** [comment]
Hi @cmark,
thanks again for your help.

I was able to make progress with the delta updates, but I'm now stuck with one specific archive.
It's the Delta Snomed UK Release of May 2020 (here https://isd.digital.nhs.uk/trud3/user/authenticated/group/0/pack/26/subpack/104/releases). 

I am getting a lot of validation errors referring to missing IDs contained in the file der2_cRefset_CareRecordElementDelta_GB_20200513.txt.
After several attempt of fixing the file manually, I attempted to import the archive without that file. Unfortunately I'm now experiencing a different issue: the import fails because it detect an already existing MAIN/2018-07-31/SNOMEDCT-UK/2020-05-01 branch, which I believe is created by the import itself.

I wanted to check if you tried to use this archive and if you run into the same issues.

Thanks,
Cristina

**Comment by cmark** [comment]
Hi @cristinacivili-work,

I'm happy to hear you were able to make progress.

Yes, UK RefSets often refer content from another extension, especially if the member is coming from the UK EDITION.
There are two ways to resolve such errors:

1. Remove those lines from the RF2 archive: in case you don't need that content, feel free to remove it, to help you identify lines like that we have made a small change to allow the importer to run in `dryRun` mode, just validate the archive against the current data and skip the import phase. See the branch here: https://github.com/b2ihealthcare/snow-owl/tree/feature/SO-4483-support-dry-run-rf2-import

2. Import the required content first or merge the required content with the RF2 archive you have, resulting in a single RF2 import file and import that. There is a tool that might be helpful in such cases: https://github.com/b2ihealthcare/rf2-d2

Yes, we are maintaining servers with all the UK data up to the most recent releases (both 2020-08-05 and 2020-10-28) and we have identified those issues as well and in order to import them, we had to fix them first in the RF2 archive. 

I hope this helps and as always feel free to reach us if you run into any issues.

Cheers,
Mark

**Comment by cmark** [comment]
Hi @cristinacivili-work,

FYI: The latest version has an improved RF2 import API, where you will be able to run the import process in `dryRun` mode, where only the validation phase is going to be executed and the actual import will be skipped. The response object should also contain information about potential import file defects and aid you in locating and resolving them.

Let us know what you think.

Cheers,
Mark
