### ISSUE TITLE
Concept Search API semanticTag filter issue

### ISSUE THREAD

**Issue by cmark** [b2ihealthcare/snow-owl#738]
**Describe the bug**
Applying both the `term` and `semanticTag` filter parameters might return fewer results because the semantic tag is applied to the internal description search and not to the concept search.

See discussion #737 for further details.

**To Reproduce**
```
POST /snomed-ct/v3/MAIN/concepts/search
{
  "active": true,
  "expand": "fsn()",
  "limit": 10,
  "term": "Achalasia of oesophagus"
  "semanticTag": [
    "disorder"
  ]
}
```

This returns an empty list but there is at least one concept that has a description `Achalasia of oesophagus` and the semantic tag `disorder`. 

**Expected behavior**
The `semanticTag` filter should be applied to the concept search as opposed to the description search returning all concepts that have at least one active description with the given semanticTag value.

**Version**
 - Snow Owl Version: 7.14.0
 - Elasticsearch Version (external): 7.10.0

**Comment by apeteri** [comment]
It is possible for a concept to have an FSN in multiple languages; in such cases, which semantic tag would we assign to the concept? Would it be OK to return a result for eg. `stomach` and `trastorno` (Spanish for "disorder")?

**Comment by cmark** [comment]
We will either index all active FSN semanticTags on the concept in an array or run two description searches, one for the semanticTag filter and one for the term filter (which can be costly). We already have the preferredDescriptions indexed, so we could improve that as well, adding a semanticTag field to it and searching that instead.

**Comment by cmark** [comment]
Fixed in commit https://github.com/b2ihealthcare/snow-owl/commit/645f6a8d82ebdb1c26995e1b6d0bac46fa2641c8.
