### ISSUE TITLE
Contribution by code smell removal

### ISSUE THREAD

**Issue by EranHashmo** [b2ihealthcare/snow-owl#797]
Hi

I am a cs student attending a course in open source.
As a part of the course, I am participating in an experiment about smells in code.

The task I was given is to contribute to an open source project by removing smells found by checkstyle. 
May I contribute to this project?

The smell I would like to remove is an NPath complexity violation at:
snomed/com.b2international.snowowl.snomed.datastore/src/com/b2international/snowowl/snomed/datastore/index/change/ConceptChangeProcessor.java

Line:  305, NPath complexity is 49,152

Link to the experiment article:
https://arxiv.org/pdf/2103.01861.pdf

**Comment by cmark** [comment]
Hi @EranHashmo,

Sure, go ahead, feel free to modify that class 🙂. Make sure you agree to our [CONTRIBUTION](https://github.com/b2ihealthcare/snow-owl/blob/7.x/CONTRIBUTING.md) guidelines and then use the `7.x` branch as base branch to create your PR.
If you have any questions, feel free to contact me here.

Cheers,
Mark
