### ISSUE TITLE
Support the "url" search parameter for both CodeSystem and ValueSet resources

### ISSUE THREAD

**Issue by michael-schmid1** [b2ihealthcare/snow-owl#935]
Hello,

it would be great if SnowOwl could support the "url" search parameter for CodeSystem and ValueSet resources. Reason: HAPI FHIR is a popular FHIR library (AFAIK it is the reference implementation) on the Java platform that provides a built-in resource validator that can utilize remote terminology services, i.e. SnowOwl. A precondition for this validator is that the terminology service supports the aforementioned search parameter. Detailed documentation regarding all preconditions can be found here: https://hapifhir.io/hapi-fhir/docs/validation/validation_support_modules.html#remoteterminologyservicevalidationsupport

Any thoughts on this?
BR

**Comment by cmark** [comment]
Hi @business-ms,

The most recent release [8.0.0](https://github.com/b2ihealthcare/snow-owl/releases/tag/v8.0.0) adds full support for storing and filtering by the `CodeSystem.url` (also `ValueSet.url`, `ConceptMap.url`, `Bundle.url`) property. Both `GET` and `POST` search endpoints support it. 
Could you please check if that satisfies your needs?

Cheers,
Mark

**Comment by michael-schmid1** [comment]
Now that is a fast response time :-) 
I'll try again with this version and report back here. Thanks for the response.

**Comment by cmark** [comment]
Happy to help :-)
Please note version `8.0` requires reimport of everything from scratch, there is no automated migration from `7.x` versions.

**Comment by michael-schmid1** [comment]
Perfect, this works! Thanks!
