### ISSUE TITLE
SNOMED CT Import not working

### ISSUE THREAD

**Issue by xlemassacre** [b2ihealthcare/snow-owl#936]
Hi,

in Version 8 i'm not able to import SNOMED CT anymore, the jobs fails with following error:
`"result": "{\"message\":\"Terminology Resource with identifier 'MAIN' could not be found.\",\"developerMessage\":\"The requested instance resource (id = 'MAIN', type = 'Terminology Resource') does not exist and/or not yet created.\",\"code\":0,\"status\":404,\"additionalInfo\":{}}",`

but "/snowowl/snomedct/branches" returns the following branch

```
    "items": [
        {
            "name": "MAIN",
            "parentPath": "",
            "baseTimestamp": 1636551165876,
            "headTimestamp": 1636551165876,
            "state": "UP_TO_DATE",
            "deleted": false,
            "path": "MAIN"
        }
    ]
```

Is this a problem with the current version or am i doing something wrong?

**Comment by cmark** [comment]
Hi @tpawork,

In version 8 it is required to create a SNOMED CT Code System resource before importing any RF2 files (version 7 created this automatically). You can do so by performing the following HTTP call:

```
POST /codesystems
{
  "id": "SNOMEDCT",
  "url": "[string](http://snomed.info/sct/900000000000207008)",
  "title": "SNOMED CT",
  "language": "eng",
  "status": "active",
  "branchPath": "MAIN",
  "toolingId": "snomed",
  "commitComment": "Create SNOMEDCT CodeSystem"
}
```

I hope this helps.

Cheers,
Mark

**Comment by xlemassacre** [comment]
Hi @cmark,

thanks for the fast response.
This seems to solve the problem, the import is now in state RUNNING.

Cheers, 
Thomas

**Comment by cmark** [comment]
Glad to hear. :-)

Cheers,
Mark

**Comment by xlemassacre** [comment]
Hi @cmark,

it seems that the import never comes to state complete. Today I stopped the import from yesterday (by restarting snowowl):
            "state": "FAILED",
            "completionLevel": 0,
            "deleted": false,
            "parameters": "{\"rf2Archive\":{\"attachmentId\":\"e1e0832b-e47b-43ad-ad69-9f1df111b7c5\",\"fileName\":\"file\"},\"releaseType\":\"FULL\",\"createVersions\":true,\"ignoreMissingReferencesIn\":[],\"dryRun\":false,\"operation\":\"import\",\"type\":\"SnomedRf2ImportRequest\"}",
            "elapsedTime": "15 h 41 min 38 s"

I started an import again, but it's still in state RUNNING after more than an hour. Can't find an error in the log, only following info:
Preparing RF2 import took: 17.27 min
Validating component consistency...

**Comment by cmark** [comment]
Hi @tpawork,

What kind of hardware configuration (CPU, RAM, Disk) are you trying to run Snow Owl on? Are you connecting it to an external Elasticsearch cluster? Or everything is the default Docker image (and [this](https://github.com/b2ihealthcare/snow-owl/blob/8.x/docker/docker-compose.yml) compose configuration) setup?
That 15 hour looks scary 😬, FULL imports tend to complete around an hour or so for the SNOMED International Edition on decent hardware (8 vCPU, 8-16GB RAM, SSD).

Cheers,
Mark

**Comment by xlemassacre** [comment]
I'm using the docker compose file, but i had to reduce RAM for both services to 4GB each.

Current Hardware:
2 vCPU
10 GB RAM 
SAS 

I am trying to get more vCPU and RAM now on my VM

**Comment by cmark** [comment]
I suggest importing the Snapshot release instead of the Full release first.
The minimum VM I would recommend for that docker-compose file (which runs both Snow Owl and Elasticsearch on the same machine) is `4 vCPU, 16g`. You can reduce the Elasticsearch container's memory to 4g, but leave Snow Owl at 6g or even increase it to 8g, leaving 4g free for the OS and I/O cache.
I hope this helps.

**Comment by xlemassacre** [comment]
Did the import again now with 4vCPU, 5GB RAM for elastichsearch and 7GB for Snow Owl. 
Took almost an hour but it's now in state FINISHED :-)

**Comment by cmark** [comment]
Glad to hear that. :)
